import app.kernel.memory_redaction as memory_redaction_kernel

MEMORY_REDACTION_MODES = memory_redaction_kernel.MEMORY_REDACTION_MODES
MEMORY_REDACTION_MODE_STANDARD = memory_redaction_kernel.MEMORY_REDACTION_MODE_STANDARD
MEMORY_REDACTION_MODE_STRICT = memory_redaction_kernel.MEMORY_REDACTION_MODE_STRICT
is_sensitive_redaction_key = memory_redaction_kernel.is_sensitive_redaction_key
normalize_memory_redaction_mode = memory_redaction_kernel.normalize_memory_redaction_mode
redact_memory_metadata = memory_redaction_kernel.redact_memory_metadata
redact_memory_metadata_value = memory_redaction_kernel.redact_memory_metadata_value
redact_memory_text = memory_redaction_kernel.redact_memory_text
sanitizer_unstable_assignment_suffix_length = memory_redaction_kernel.sanitizer_unstable_assignment_suffix_length
sanitizer_unstable_suffix_length = memory_redaction_kernel.sanitizer_unstable_suffix_length
