from __future__ import annotations

import app.platform.postgres.limits as postgres_limits


ARTIFACT_MANIFEST_MAX_BYTES = postgres_limits.ARTIFACT_MANIFEST_MAX_BYTES
AUDIT_PAYLOAD_MAX_BYTES = postgres_limits.AUDIT_PAYLOAD_MAX_BYTES
CONTEXT_SNAPSHOT_PAYLOAD_MAX_BYTES = postgres_limits.CONTEXT_SNAPSHOT_PAYLOAD_MAX_BYTES
MESSAGE_CONTENT_MAX_BYTES = postgres_limits.MESSAGE_CONTENT_MAX_BYTES
MESSAGE_METADATA_MAX_BYTES = postgres_limits.MESSAGE_METADATA_MAX_BYTES
PersistenceSizeLimitError = postgres_limits.PersistenceSizeLimitError
RUN_EVENT_MESSAGE_MAX_BYTES = postgres_limits.RUN_EVENT_MESSAGE_MAX_BYTES
RUN_EVENT_PAYLOAD_MAX_BYTES = postgres_limits.RUN_EVENT_PAYLOAD_MAX_BYTES
RUN_INPUT_MAX_BYTES = postgres_limits.RUN_INPUT_MAX_BYTES
RUN_RESULT_MAX_BYTES = postgres_limits.RUN_RESULT_MAX_BYTES
RUN_STEP_PAYLOAD_MAX_BYTES = postgres_limits.RUN_STEP_PAYLOAD_MAX_BYTES
compact_json_dumps = postgres_limits.compact_json_dumps
ensure_json_size = postgres_limits.ensure_json_size
ensure_text_size = postgres_limits.ensure_text_size
json_size_bytes = postgres_limits.json_size_bytes
