# Persistence implementations move to their domain owners via identity aliases.
# Run lifecycle operations are owned by app.runs; this facade no longer exports them.
# ruff: noqa: F401

from __future__ import annotations

import json
from typing import Any

from app.auth import ADMIN_ROLE_ALIASES, normalize_roles
from app.capability_distribution import (
    CapabilityAccessDecision,
    CapabilityAccessContext,
    CapabilityAuthorizationDenial,
    CapabilityDistributionSubject,
    capability_distribution_audit_payload,
    has_valid_capability_distribution_archive_evidence,
    is_capability_distribution_archived as shared_capability_distribution_archived,
    is_valid_archive_actor,
    resolve_capability_access,
)
from app.context.file_continuity import (
    compatible_reusable_file_ids,
    has_file_input_mode,
    list_authorized_session_input_files as list_authorized_session_input_files,
)
from app.control_plane_contracts import (
    ARTIFACT_MANIFEST_SCHEMA_VERSION,
    AUDIT_EVENT_SCHEMA_VERSION,
    EVENT_ENVELOPE_SCHEMA_VERSION,
    EXECUTOR_RESULT_SCHEMA_VERSION,
    HARNESS_CHAT_EXECUTOR_TYPE,
    HASH_LIKE_VALUE_PATTERN,
    LEGACY_SYNTHETIC_CHAT_SKILL_ID,
    RUN_CONTRACT_VERSION,
    RUN_EXECUTION_KIND_HARNESS_CHAT,
    RUN_EXECUTION_KIND_SKILL,
    RUN_PAYLOAD_SCHEMA_VERSION,
    RUN_PAYLOAD_SCHEMA_VERSION_V2,
    artifact_lineage_contract,
    artifact_manifest_contract,
    is_legacy_synthetic_chat_identity,
    standard_error_code,
)
from app.error_taxonomy import summarize_error_categories
from app.persistence import (
    RepositoryNotFoundError,
    artifacts,
    chat_submissions,
    file_deletions,
    object_deletions,
    retention,
)
import app.agent_apps.infrastructure.catalog_postgres as agent_catalog_persistence
import app.context.infrastructure.postgres as memory_persistence
import app.context.infrastructure.snapshot_postgres as context_snapshot_persistence
import app.context.infrastructure.sources_postgres as context_sources_persistence
import app.conversations.infrastructure.postgres as conversation_persistence
import app.identity.infrastructure.postgres as identity_persistence
import app.mcp.infrastructure.registry_postgres as mcp_registry_persistence
import app.platform.postgres.errors as postgres_errors
import app.runs.infrastructure.postgres as run_persistence
import app.skills.infrastructure.legacy_workbench as legacy_workbench_persistence
import app.skills.infrastructure.postgres as skill_persistence
from app.platform.postgres.errors import RepositoryConflictError
from app.persistence_limits import (
    ARTIFACT_MANIFEST_MAX_BYTES,
    AUDIT_PAYLOAD_MAX_BYTES,
    CONTEXT_SNAPSHOT_PAYLOAD_MAX_BYTES,  # noqa: F401
    MESSAGE_CONTENT_MAX_BYTES,  # noqa: F401 - legacy compatibility export
    MESSAGE_METADATA_MAX_BYTES,  # noqa: F401 - legacy compatibility export
    RUN_INPUT_MAX_BYTES,
    RUN_RESULT_MAX_BYTES,
    RUN_STEP_PAYLOAD_MAX_BYTES,
    PersistenceSizeLimitError,
    compact_json_dumps,
    ensure_json_size,
    ensure_text_size,
)
from app.projection_redaction import sanitize_user_control_input, strip_server_owned_control_metadata
from app import run_event_repository as _run_event_repository
from app.skills.dependencies import PUBLIC_WORKBENCH_SKILL_IDS, is_workbench_skill_public
from app.skills.lifecycle import is_user_runnable_status
from app.skills.pinning import (
    SKILL_PINNED_SNAPSHOT_GOVERNANCE_SCHEMA_VERSION_V1,
    SKILL_PINNED_SNAPSHOT_GOVERNANCE_SCHEMA_VERSION_V2,
    SkillVersionMaterializationError,
    build_skill_manifest_ref,
    build_skill_manifest_refs,
    build_skill_snapshot_governance,  # noqa: F401 - migration bridge AST compatibility
    skill_manifest_materialization_sha256,
    validate_skill_manifest_refs,
)
from app.skills.release_policy import resolve_rollout_skill_decision
from app.tool_policy import evaluate_tool_policy, max_risk
from app.validation import SAFE_ID_PATTERN  # noqa: F401

import app.platform.postgres.values as postgres_values
import app.skills.infrastructure.resolution_postgres as skills_resolution_persistence
import app.mcp.infrastructure.tool_policies_postgres as mcp_tool_policies_persistence
import app.skills.infrastructure.catalog_postgres as skills_catalog_persistence
import app.skills.infrastructure.file_overlays_postgres as skills_file_overlays_persistence
import app.agent_apps.infrastructure.principal_catalog_postgres as agent_apps_principal_catalog_persistence
import app.mcp.infrastructure.chat_access_postgres as mcp_chat_access_persistence
import app.identity.infrastructure.capability_distributions_postgres as identity_capability_distributions_persistence
import app.runs.infrastructure.capability_admission_postgres as runs_capability_admission_persistence
import app.identity.infrastructure.audit_postgres as identity_audit_persistence
import app.conversations.infrastructure.session_queries_postgres as conversations_session_queries_persistence
import app.runs.infrastructure.creation_postgres as runs_creation_persistence
import app.runs.infrastructure.control_operations_postgres as runs_control_operations_persistence
import app.streaming.infrastructure.run_events_postgres as streaming_run_events_persistence
import app.sandbox.infrastructure.leases_postgres as sandbox_leases_persistence
import app.artifacts.infrastructure.records_postgres as artifacts_records_persistence
import app.skills.infrastructure.run_snapshots_postgres as skills_run_snapshots_persistence
import app.skills.infrastructure.versions_postgres as skills_versions_persistence
import app.runs.infrastructure.steps_postgres as runs_steps_persistence
import app.runs.infrastructure.admin_queries_postgres as runs_admin_queries_persistence
import app.runs.infrastructure.replay_postgres as runs_replay_persistence
import app.files.infrastructure.run_bindings_postgres as files_run_bindings_persistence

claim_object_deletions = object_deletions.claim_object_deletions
complete_object_deletion = object_deletions.complete_object_deletion
fail_object_deletion = object_deletions.fail_object_deletion
requeue_dead_letter_object_deletion = object_deletions.requeue_dead_letter_object_deletion
ObjectDeletionStateError = object_deletions.ObjectDeletionStateError
FileDeletionBlockedError = file_deletions.FileDeletionBlockedError
queue_unbound_file_for_deletion = file_deletions.queue_unbound_file_for_deletion
get_admin_artifact = artifacts.get_admin_artifact
get_artifact = artifacts.get_artifact
get_authorized_artifact = artifacts.get_authorized_artifact
list_revealed_artifact_sessions = artifacts.list_revealed_artifact_sessions
list_revealed_artifacts = artifacts.list_revealed_artifacts
queue_expired_artifacts_for_deletion = artifacts.queue_expired_artifacts_for_deletion
get_data_retention_backlog = retention.get_data_retention_backlog
purge_deleted_memory_records = retention.purge_deleted_memory_records
get_agent = agent_catalog_persistence.get_agent
get_tenant_profile_validation_agent = (
    agent_catalog_persistence.get_tenant_profile_validation_agent
)
list_lambchat_agents = agent_catalog_persistence.list_lambchat_agents
append_message = conversation_persistence.append_message
create_session = conversation_persistence.create_session
ensure_workspace_belongs_to_tenant = (
    conversation_persistence.ensure_workspace_belongs_to_tenant
)
get_authorized_lambchat_session = conversation_persistence.get_authorized_lambchat_session
get_authorized_session_projection = conversation_persistence.get_authorized_session_projection
get_session_for_action = conversation_persistence.get_session_for_action
list_authorized_messages = conversation_persistence.list_authorized_messages
list_authorized_sessions = conversation_persistence.list_authorized_sessions
list_authorized_user_messages_for_runs = (
    conversation_persistence.list_authorized_user_messages_for_runs
)
list_session_messages_for_fork = conversation_persistence.list_session_messages_for_fork
mark_session_deleted = conversation_persistence.mark_session_deleted
update_session_title = conversation_persistence.update_session_title
MEMORY_RETENTION_CLEANUP_CURSOR_KEY = memory_persistence.MEMORY_RETENTION_CLEANUP_CURSOR_KEY
_default_memory_policy = memory_persistence._default_memory_policy
_list_expired_memory_cleanup_scopes = memory_persistence._list_expired_memory_cleanup_scopes
_memory_policy_from_row = memory_persistence._memory_policy_from_row
_stored_memory_redaction_mode = memory_persistence._stored_memory_redaction_mode
_validated_memory_redaction_mode = memory_persistence._validated_memory_redaction_mode
admin_delete_memory_record = memory_persistence.admin_delete_memory_record
cleanup_expired_memory_records = memory_persistence.cleanup_expired_memory_records
cleanup_expired_memory_records_across_scopes = memory_persistence.cleanup_expired_memory_records_across_scopes
create_memory_record = memory_persistence.create_memory_record
delete_memory_record = memory_persistence.delete_memory_record
get_effective_memory_policy = memory_persistence.get_effective_memory_policy
list_admin_memory_policies = memory_persistence.list_admin_memory_policies
list_admin_memory_records = memory_persistence.list_admin_memory_records
list_memory_records = memory_persistence.list_memory_records
list_scoped_context_memory_records = memory_persistence.list_scoped_context_memory_records
memory_policy_id = memory_persistence.memory_policy_id
set_memory_policy = memory_persistence.set_memory_policy
CONTEXT_SNAPSHOT_MEMBER_BATCH_LIMIT = context_snapshot_persistence.CONTEXT_SNAPSHOT_MEMBER_BATCH_LIMIT
_normalize_context_snapshot_member_ids = context_snapshot_persistence._normalize_context_snapshot_member_ids
create_context_snapshot = context_snapshot_persistence.create_context_snapshot
get_bound_executor_context_snapshot = context_snapshot_persistence.get_bound_executor_context_snapshot
get_context_snapshot_for_worker = context_snapshot_persistence.get_context_snapshot_for_worker
get_latest_authorized_executor_context_snapshot = context_snapshot_persistence.get_latest_authorized_executor_context_snapshot
list_context_share_snapshots_for_target_session = context_snapshot_persistence.list_context_share_snapshots_for_target_session
list_context_snapshots = context_snapshot_persistence.list_context_snapshots
update_run_context_snapshot_ref = context_snapshot_persistence.update_run_context_snapshot_ref
count_session_context_messages = context_sources_persistence.count_session_context_messages
get_scoped_context_artifact = context_sources_persistence.get_scoped_context_artifact
get_scoped_context_file = context_sources_persistence.get_scoped_context_file
list_authorized_context_file_rows = (
    context_sources_persistence.list_authorized_context_file_rows
)
list_scoped_context_messages = context_sources_persistence.list_scoped_context_messages
list_session_context_artifacts = (
    context_sources_persistence.list_session_context_artifacts
)
list_session_context_files = context_sources_persistence.list_session_context_files
list_session_context_messages = (
    context_sources_persistence.list_session_context_messages
)
session_has_legacy_run_history = (
    context_sources_persistence.session_has_legacy_run_history
)
ensure_submission_principal = identity_persistence.ensure_submission_principal
ensure_user = identity_persistence.ensure_user
get_user = identity_persistence.get_user
tenant_exists = identity_persistence.tenant_exists
acquire_user_active_run_admission_lock = (
    run_persistence.acquire_user_active_run_admission_lock
)
count_active_runs_for_user = run_persistence.count_active_runs_for_user
enforce_user_active_run_admission = run_persistence.enforce_user_active_run_admission
enforce_user_active_run_admission_under_lock = (
    run_persistence.enforce_user_active_run_admission_under_lock
)
get_active_resume_for_source_run = run_persistence.get_active_resume_for_source_run
get_active_retry_for_source_run = run_persistence.get_active_retry_for_source_run
get_run = run_persistence.get_run
get_run_identity = run_persistence.get_run_identity
RepositoryAuthorizationError = postgres_errors.RepositoryAuthorizationError
canonical_builtin_tool_identities = skill_persistence.canonical_builtin_tool_identities
get_skill_version = skill_persistence.get_skill_version
run_skill_snapshot_source_json = skill_persistence.run_skill_snapshot_source_json
validate_replay_skill_manifests = skill_persistence.validate_replay_skill_manifests
_mcp_server_projection = mcp_registry_persistence._mcp_server_projection
_json_dict_projection = mcp_registry_persistence._json_dict_projection
_json_string_list_projection = mcp_registry_persistence._json_string_list_projection
list_mcp_server_registry = mcp_registry_persistence.list_mcp_server_registry
list_tenant_mcp_server_registry = mcp_registry_persistence.list_tenant_mcp_server_registry
list_mcp_server_registry_names = mcp_registry_persistence.list_mcp_server_registry_names
upsert_mcp_server_registry = mcp_registry_persistence.upsert_mcp_server_registry
toggle_mcp_server_registry = mcp_registry_persistence.toggle_mcp_server_registry
delete_mcp_server_registry = mcp_registry_persistence.delete_mcp_server_registry
record_mcp_server_credential = mcp_registry_persistence.record_mcp_server_credential
list_workbench_capabilities = legacy_workbench_persistence.list_workbench_capabilities
list_workbench_skills = legacy_workbench_persistence.list_workbench_skills
# Preserve the established repository facade used by Chat callers while making
# the cross-module ownership explicit to Ruff.
chat_submission_fingerprint = chat_submissions.chat_submission_fingerprint
claim_chat_submission = chat_submissions.claim_chat_submission
finalize_chat_submission = chat_submissions.finalize_chat_submission
get_chat_submission = chat_submissions.get_chat_submission
DEFAULT_RUN_EXECUTOR_TYPES = skills_resolution_persistence.DEFAULT_RUN_EXECUTOR_TYPES
ACTIVE_RUN_STATUSES = runs_creation_persistence.ACTIVE_RUN_STATUSES
RETRYABLE_RUN_STATUSES = runs_creation_persistence.RETRYABLE_RUN_STATUSES
RUN_CONTROL_OPERATION_ACTIONS = runs_control_operations_persistence.RUN_CONTROL_OPERATION_ACTIONS


new_id = postgres_values.new_id


_require_json_size = postgres_values._require_json_size


_require_text_size = postgres_values._require_text_size


dumps_json = postgres_values.dumps_json


_parse_iso_datetime = postgres_values._parse_iso_datetime


_coerce_int = postgres_values._coerce_int


_coerce_bool = postgres_values._coerce_bool


_effective_status = mcp_tool_policies_persistence._effective_status


_tool_policy_projection = mcp_tool_policies_persistence._tool_policy_projection


_repository_ledger_conflict = streaming_run_events_persistence._repository_ledger_conflict


_required_schema_version = runs_admin_queries_persistence._required_schema_version




_resolve_executable_skill = skills_resolution_persistence._resolve_executable_skill


resolve_agent_skill = skills_resolution_persistence.resolve_agent_skill


resolve_selected_skill = skills_resolution_persistence.resolve_selected_skill


ensure_mcp_tool_active = mcp_tool_policies_persistence.ensure_mcp_tool_active




_principal_skill_release_decision = skills_versions_persistence._principal_skill_release_decision


list_principal_lambchat_agents = agent_apps_principal_catalog_persistence.list_principal_lambchat_agents


get_skill = skills_catalog_persistence.get_skill


list_skill_ids = skills_catalog_persistence.list_skill_ids


_upsert_workbench_skill_status = skills_catalog_persistence._upsert_workbench_skill_status


set_workbench_skill_status = skills_catalog_persistence.set_workbench_skill_status


set_uploaded_workbench_skill_status = skills_catalog_persistence.set_uploaded_workbench_skill_status


list_public_skill_catalog = skills_catalog_persistence.list_public_skill_catalog


set_public_skill_enabled = skills_catalog_persistence.set_public_skill_enabled


list_user_skill_file_overlays = skills_file_overlays_persistence.list_user_skill_file_overlays


upsert_user_skill_file = skills_file_overlays_persistence.upsert_user_skill_file


delete_user_skill_file = skills_file_overlays_persistence.delete_user_skill_file


list_chat_mcp_tool_catalog_entries = mcp_chat_access_persistence.list_chat_mcp_tool_catalog_entries


_chat_mcp_access_context = mcp_chat_access_persistence._chat_mcp_access_context


_authorize_chat_mcp_tool_entry = mcp_chat_access_persistence._authorize_chat_mcp_tool_entry








_capability_distribution_string_list = identity_capability_distributions_persistence._capability_distribution_string_list


_capability_distribution_json = identity_capability_distributions_persistence._capability_distribution_json


_capability_distribution_projection = identity_capability_distributions_persistence._capability_distribution_projection


is_capability_distribution_archived = identity_capability_distributions_persistence.is_capability_distribution_archived


_acquire_capability_distribution_lifecycle_lock = identity_capability_distributions_persistence._acquire_capability_distribution_lifecycle_lock


acquire_capability_distribution_lifecycle_locks = identity_capability_distributions_persistence.acquire_capability_distribution_lifecycle_locks


_lock_capability_distribution_metadata = identity_capability_distributions_persistence._lock_capability_distribution_metadata


_require_unarchived_capability_distribution = identity_capability_distributions_persistence._require_unarchived_capability_distribution


_raise_distribution_update_failure = identity_capability_distributions_persistence._raise_distribution_update_failure


ensure_tenant_capability_distribution_backfill = identity_capability_distributions_persistence.ensure_tenant_capability_distribution_backfill


list_capability_distribution_rows = identity_capability_distributions_persistence.list_capability_distribution_rows


get_capability_distribution_row = identity_capability_distributions_persistence.get_capability_distribution_row


upsert_capability_distribution_row = identity_capability_distributions_persistence.upsert_capability_distribution_row


archive_capability_distribution_row = identity_capability_distributions_persistence.archive_capability_distribution_row


toggle_capability_distribution_row = identity_capability_distributions_persistence.toggle_capability_distribution_row


set_capability_distribution_status = identity_capability_distributions_persistence.set_capability_distribution_status


_capability_not_authorized = identity_capability_distributions_persistence._capability_not_authorized


_MCP_TOOL_ID_KEYS = runs_capability_admission_persistence._MCP_TOOL_ID_KEYS
_CALLER_AUTH_SNAPSHOT_KEY_ALIASES = runs_capability_admission_persistence._CALLER_AUTH_SNAPSHOT_KEY_ALIASES


_append_explicit_mcp_tool_ids = runs_capability_admission_persistence._append_explicit_mcp_tool_ids


_explicit_mcp_tool_scope = runs_capability_admission_persistence._explicit_mcp_tool_scope


extract_run_mcp_tool_ids = runs_capability_admission_persistence.extract_run_mcp_tool_ids


run_mcp_tool_ids_for_skill = runs_capability_admission_persistence.run_mcp_tool_ids_for_skill


strip_caller_run_auth_snapshot_fields = runs_capability_admission_persistence.strip_caller_run_auth_snapshot_fields


normalize_run_input_for_enqueue = runs_capability_admission_persistence.normalize_run_input_for_enqueue


_authorize_run_capabilities = runs_capability_admission_persistence._authorize_run_capabilities


authorize_run_capabilities = runs_capability_admission_persistence.authorize_run_capabilities


authorize_selected_run_capabilities = runs_capability_admission_persistence.authorize_selected_run_capabilities


authorize_replay_run_capabilities = runs_capability_admission_persistence.authorize_replay_run_capabilities


pinned_replay_mcp_tool_ids = runs_capability_admission_persistence.pinned_replay_mcp_tool_ids


require_replay_source_identity = runs_capability_admission_persistence.require_replay_source_identity
















list_admin_tool_policies = mcp_tool_policies_persistence.list_admin_tool_policies


list_admin_tool_policy_history = mcp_tool_policies_persistence.list_admin_tool_policy_history


list_role_governance_audit_history = identity_audit_persistence.list_role_governance_audit_history


upsert_admin_tool_policy = mcp_tool_policies_persistence.upsert_admin_tool_policy


ensure_workspace = conversations_session_queries_persistence.ensure_workspace


allocate_session_run_generation = runs_creation_persistence.allocate_session_run_generation


create_run = runs_creation_persistence.create_run


update_run_auth_snapshot = runs_creation_persistence.update_run_auth_snapshot


_validated_run_control_operation_identity = runs_control_operations_persistence._validated_run_control_operation_identity


acquire_run_control_operation_lock = runs_control_operations_persistence.acquire_run_control_operation_lock


get_run_control_operation = runs_control_operations_persistence.get_run_control_operation


record_run_control_operation = runs_control_operations_persistence.record_run_control_operation






append_event = streaming_run_events_persistence.append_event


append_event_batch = streaming_run_events_persistence.append_event_batch


acquire_run_event_terminal_drain_fence = streaming_run_events_persistence.acquire_run_event_terminal_drain_fence


get_authorized_run = runs_creation_persistence.get_authorized_run


get_authorized_session = conversations_session_queries_persistence.get_authorized_session


get_authorized_context_target_session = conversations_session_queries_persistence.get_authorized_context_target_session


list_run_events = streaming_run_events_persistence.list_run_events












































get_sandbox_lease = sandbox_leases_persistence.get_sandbox_lease


renew_sandbox_lease = sandbox_leases_persistence.renew_sandbox_lease


list_active_sandbox_leases_for_run = sandbox_leases_persistence.list_active_sandbox_leases_for_run


list_current_sandbox_runtime_leases_for_attempt = sandbox_leases_persistence.list_current_sandbox_runtime_leases_for_attempt


list_terminal_sandbox_runtime_leases_for_attempt = _run_event_repository.list_terminal_sandbox_runtime_leases_for_attempt


list_sandbox_leases_for_run = sandbox_leases_persistence.list_sandbox_leases_for_run


record_sandbox_runtime_cleanup_outcome = sandbox_leases_persistence.record_sandbox_runtime_cleanup_outcome


list_sandbox_leases = sandbox_leases_persistence.list_sandbox_leases


list_run_artifacts = artifacts_records_persistence.list_run_artifacts


upsert_run_skill_snapshot = skills_run_snapshots_persistence.upsert_run_skill_snapshot


pin_primary_skill_mcp_tool_ids = skills_run_snapshots_persistence.pin_primary_skill_mcp_tool_ids


insert_run_skill_snapshots_at_creation = skills_run_snapshots_persistence.insert_run_skill_snapshots_at_creation


skill_manifest_refs = skills_run_snapshots_persistence.skill_manifest_refs


materialize_run_skill_manifests = skills_run_snapshots_persistence.materialize_run_skill_manifests


list_run_skill_snapshots = skills_run_snapshots_persistence.list_run_skill_snapshots


validate_run_skill_snapshots_for_dispatch = skills_run_snapshots_persistence.validate_run_skill_snapshots_for_dispatch


_sanitize_skill_snapshot_source = skills_run_snapshots_persistence._sanitize_skill_snapshot_source


_sanitize_skill_snapshot = skills_run_snapshots_persistence._sanitize_skill_snapshot


_skill_usage_from_events = skills_run_snapshots_persistence._skill_usage_from_events


_attach_skill_usage = skills_run_snapshots_persistence._attach_skill_usage


_json_dict = skills_versions_persistence._json_dict


_json_list = skills_versions_persistence._json_list


_project_skill_version = skills_versions_persistence._project_skill_version


_project_skill_release_policy = skills_versions_persistence._project_skill_release_policy


upsert_skill_version = skills_versions_persistence.upsert_skill_version


create_skill_catalog = skills_versions_persistence.create_skill_catalog


update_skill_catalog_version = skills_versions_persistence.update_skill_catalog_version


backfill_builtin_skill_version_snapshot = skills_versions_persistence.backfill_builtin_skill_version_snapshot


update_skill_version_status = skills_versions_persistence.update_skill_version_status


get_effective_skill_version_for_policy = skills_versions_persistence.get_effective_skill_version_for_policy


list_skill_versions = skills_versions_persistence.list_skill_versions


get_skill_release_policy = skills_versions_persistence.get_skill_release_policy


set_skill_release_policy = skills_versions_persistence.set_skill_release_policy


diff_skill_versions = skills_versions_persistence.diff_skill_versions


list_admin_skill_summaries = skills_versions_persistence.list_admin_skill_summaries


get_admin_skill_detail = skills_versions_persistence.get_admin_skill_detail


upsert_run_step = runs_steps_persistence.upsert_run_step


































list_run_steps = runs_steps_persistence.list_run_steps


list_admin_runs = runs_admin_queries_persistence.list_admin_runs


get_admin_runtime_run_summary = runs_admin_queries_persistence.get_admin_runtime_run_summary


get_admin_runtime_admission_summary = runs_admin_queries_persistence.get_admin_runtime_admission_summary


get_admin_runtime_observability_summary = runs_admin_queries_persistence.get_admin_runtime_observability_summary


_SANDBOX_LEASE_RUNTIME_HANDLE_PROJECTION_KEYS = runs_admin_queries_persistence._SANDBOX_LEASE_RUNTIME_HANDLE_PROJECTION_KEYS


_sandbox_lease_payload_projection = runs_admin_queries_persistence._sandbox_lease_payload_projection


_sandbox_lease_admin_projection = runs_admin_queries_persistence._sandbox_lease_admin_projection


get_admin_run_detail = runs_admin_queries_persistence.get_admin_run_detail






copy_run_as_new_task = runs_replay_persistence.copy_run_as_new_task


retry_run_as_new_task = runs_replay_persistence.retry_run_as_new_task


resume_run_as_new_task = runs_replay_persistence.resume_run_as_new_task


copied_run_execution_snapshot = runs_replay_persistence.copied_run_execution_snapshot


preserved_server_owned_execution_snapshot = runs_replay_persistence.preserved_server_owned_execution_snapshot


admitted_agent_profile_pins_for_copy = runs_replay_persistence.admitted_agent_profile_pins_for_copy


update_run_input_execution_snapshot = runs_replay_persistence.update_run_input_execution_snapshot


_completed_steps_for_resume = runs_replay_persistence._completed_steps_for_resume


create_file = files_run_bindings_persistence.create_file


authorize_files_for_run = files_run_bindings_persistence.authorize_files_for_run


bind_files_to_run = files_run_bindings_persistence.bind_files_to_run


get_file = files_run_bindings_persistence.get_file












_cancel_open_run_steps = runs_steps_persistence._cancel_open_run_steps


_fail_open_run_steps = runs_steps_persistence._fail_open_run_steps


create_artifact = artifacts_records_persistence.create_artifact


append_audit_log = identity_audit_persistence.append_audit_log


append_capability_authorization_denial_audit = identity_audit_persistence.append_capability_authorization_denial_audit


list_authorized_session_runs = conversations_session_queries_persistence.list_authorized_session_runs


get_latest_authorized_session_run_input = conversations_session_queries_persistence.get_latest_authorized_session_run_input


# MCP catalog persistence and Chat-selection ownership live in app.mcp.repository.
# Keep these established names for Chat, Agent Apps, and worker call sites outside
# the re-chartered path set.
from app.mcp import repository as _mcp_repository  # noqa: E402

authorize_selected_chat_mcp_tools = _mcp_repository.authorize_selected_chat_mcp_tools
get_mcp_tool_registry_entry = _mcp_repository.get_mcp_tool_registry_entry
list_authorized_chat_mcp_tools = _mcp_repository.list_authorized_chat_mcp_tools
list_workbench_mcp_tools = _mcp_repository.list_workbench_mcp_tools
mcp_runtime_metadata_usable = _mcp_repository.mcp_runtime_metadata_usable
