from functools import lru_cache
from typing import Literal

from pydantic import Field
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_file=".env", extra="ignore")

    database_url: str = Field(default="postgresql://ai_platform:ai_platform_dev_password@localhost:54329/ai_platform")
    database_pool_min_size: int = Field(default=1)
    database_pool_max_size: int = Field(default=10)
    database_pool_timeout_seconds: float = Field(default=10.0)
    database_pool_max_waiting: int = Field(default=100)
    database_pool_close_timeout_seconds: float = Field(default=5.0)
    redis_url: str = Field(default="redis://localhost:63799/0")
    redis_max_connections: int = Field(default=10, ge=1)
    datastore_readiness_timeout_seconds: float = Field(default=2.0, gt=0, le=30)
    queue_key_prefix: str = Field(default="ai-platform:runs")

    s3_endpoint_url: str = Field(default="http://localhost:9009")
    s3_access_key_id: str = Field(default="ai_platform_minio")
    s3_secret_access_key: str = Field(default="ai_platform_minio_password")
    s3_bucket: str = Field(default="ai-platform-artifacts")
    s3_region: str = Field(default="us-east-1")

    sandbox_workspace_root: str = Field(default="/tmp/ai-platform-sandbox-workspaces")
    sandbox_container_provider: str = Field(default="fake")
    # OpenSandbox has one production security contract. Keeping this as a
    # single-value Literal makes stale trusted_internal deployment settings
    # fail during process startup instead of silently selecting a weaker path.
    sandbox_security_profile: Literal["governed"] = Field(default="governed")
    sandbox_executor_image: str = Field(default="ai-platform-executor:dev")
    sandbox_executor_browser_image: str = Field(default="")
    sandbox_executor_published_host: str = Field(default="127.0.0.1")
    sandbox_callback_base_url: str = Field(default="http://127.0.0.1:8000")
    sandbox_callback_token: str = Field(default="")
    sandbox_egress_policy_enabled: bool = Field(default=False)
    sandbox_egress_network_name: str = Field(default="ai-platform-sandbox-egress-internal-v1")
    sandbox_egress_proof_signing_key: str = Field(default="")
    sandbox_egress_proof_key_id: str = Field(default="current")
    sandbox_egress_proof_previous_keys_json: str = Field(default="")
    ai_platform_runtime_commit: str = Field(default="")
    sandbox_callback_host_gateway: str = Field(default="host.docker.internal")
    sandbox_container_start_timeout_seconds: int = Field(default=30)
    sandbox_executor_health_timeout_seconds: int = Field(default=60)
    opensandbox_domain: str = Field(default="127.0.0.1:8080")
    opensandbox_protocol: str = Field(default="http")
    opensandbox_api_key: str = Field(default="")
    opensandbox_use_server_proxy: bool = Field(default=False)
    opensandbox_request_timeout_seconds: float = Field(default=30.0)
    opensandbox_attestation_path: str = Field(default="")
    opensandbox_attestation_contract_version: str = Field(default="")
    opensandbox_attestation_timeout_seconds: float = Field(default=2.0)
    opensandbox_timeout_seconds: int = Field(default=1800)
    opensandbox_executor_image: str = Field(default="")
    opensandbox_executor_entrypoint: str = Field(default="/app/docker-entrypoint.sh uvicorn")
    opensandbox_workspace_mount_enabled: bool = Field(default=True)
    opensandbox_startup_io_probe_enabled: bool = Field(default=True)
    opensandbox_allowed_egress_hosts: str = Field(default="")
    sandbox_runtime_subject: str = Field(default="")
    opensandbox_external_egress_capability_url: str = Field(default="")
    opensandbox_external_egress_capability_token: str = Field(default="")
    opensandbox_external_egress_gateway_policy_subject: str = Field(default="")
    opensandbox_external_egress_callback_boundary_subject: str = Field(default="")
    opensandbox_external_egress_callback_base_url: str = Field(default="")
    opensandbox_external_egress_openai_base_url: str = Field(default="")
    opensandbox_external_egress_anthropic_base_url: str = Field(default="")
    opensandbox_executor_image_digest: str = Field(default="")
    sandbox_max_active_ephemeral_containers: int = Field(default=2)
    sandbox_max_active_persistent_containers: int = Field(default=1)
    max_active_runs_per_user: int = Field(default=3)
    max_active_worker_runs: int = Field(default=10)
    queue_tenant_processing_limit: int = Field(default=0)
    queue_user_processing_limit: int = Field(default=0)
    queue_lease_scan_limit: int = Field(default=50)
    queue_insight_scan_limit: int = Field(default=500)
    queue_lease_visibility_timeout_seconds: int = Field(default=900)
    queue_metadata_fallback_scan_limit: int = Field(default=500)
    queue_dead_letter_max_entries: int = Field(default=1000, ge=1, le=100000)
    worker_heartbeat_ttl_seconds: float = Field(default=60.0)
    worker_maintenance_interval_seconds: float = Field(default=30.0)
    stale_run_reconciliation_seconds: int = Field(default=900, ge=60, le=86400)
    stale_run_reconciliation_limit: int = Field(default=20, ge=1, le=50)
    stale_run_reconciliation_fence_ttl_seconds: int = Field(default=300, ge=30, le=3600)
    worker_concurrency: int = Field(default=10)
    memory_retention_worker_cleanup_enabled: bool = Field(default=True)
    memory_retention_worker_cleanup_interval_seconds: float = Field(default=300.0)
    memory_retention_worker_cleanup_limit: int = Field(default=200)
    run_event_stream_max_heartbeats: int = Field(default=3600)
    default_tenant_id: str = Field(default="default")
    default_workspace_id: str = Field(default="default")
    cors_allow_origins: str = Field(
        default="http://localhost:9527,http://127.0.0.1:9527,http://10.56.0.211:8080,http://10.56.0.211:18001"
    )
    trusted_principal_secret: str = Field(default="")
    frontend_poc_auth_enabled: bool = Field(default=False)
    existing_auth_base_url: str = Field(default="http://10.56.0.25:7263")
    existing_user_info_base_url: str = Field(default="http://10.56.0.25:5166")
    existing_auth_timeout_seconds: float = Field(default=15.0)
    ai_admin_work_ids: str = Field(default="")
    ai_session_secret: str = Field(default="")
    ai_session_cookie_name: str = Field(default="ai_platform_session")
    ai_session_cookie_secure: bool = Field(default=False)
    ai_session_max_age_seconds: int = Field(default=8 * 60 * 60)
    auth_context_secret: str = Field(default="")
    auth_context_cookie_name: str = Field(default="ai_platform_auth_context")
    auth_context_cookie_secure: bool = Field(default=False)
    auth_context_max_age_seconds: int = Field(default=8 * 60 * 60)
    auth_context_lease_seconds: int = Field(default=90)
    artifact_default_retention_days: int = Field(default=90)

    # The user JWT remains short-lived; the same rotating keyring also seals
    # write-only static MCP connection headers stored by the registry.
    mcp_context_encryption_keys_json: str = Field(default="")
    mcp_context_encryption_key: str = Field(default="")
    mcp_context_current_key_id: str = Field(default="current")
    mcp_context_ttl_seconds: int = Field(default=300, ge=1, le=300)
    mcp_context_lease_seconds: int = Field(default=1800, ge=1, le=1800)
    mcp_relay_timeout_seconds: float = Field(default=30.0, gt=0, le=120)
    mcp_relay_max_response_bytes: int = Field(default=1024 * 1024, ge=1024, le=16 * 1024 * 1024)

    llm_gateway_provider: str = Field(default="openai_compatible")
    model_gateway_request_concurrency_limit: int = Field(default=0)
    openai_base_url: str = Field(default="")
    openai_api_key: str = Field(default="")
    openai_model: str = Field(default="deepseek-v4-flash")
    anthropic_base_url: str = Field(default="")
    anthropic_auth_token: str = Field(default="")
    anthropic_model: str = Field(default="deepseek-v4-flash")
    claude_agent_model: str = Field(default="deepseek-v4-flash")
    default_model_id: str = Field(default="")
    model_catalog_json: str = Field(default="")
    claude_agent_sdk_enabled: bool = Field(default=False)
    claude_agent_sdk_timeout_seconds: float = Field(default=120.0)
    claude_agent_sdk_max_turns: int = Field(default=128)
    claude_agent_sdk_effort: str = Field(default="xhigh")
    claude_agent_sdk_max_thinking_tokens: int = Field(default=16384)
    claude_agent_allowed_tools: str = Field(default="Read,Glob,LS")
    claude_agent_disallowed_tools: str = Field(default="Write,Edit,NotebookEdit")
    claude_agent_permission_mode: str = Field(default="dontAsk")
    claude_agent_workspace_root: str = Field(default="/tmp/ai-platform-agent-workspaces")
    claude_agent_sdk_skills: str = Field(default="")
    platform_skills_root: str = Field(default="skills")
    skill_staging_subdir: str = Field(default=".claude/skills")
    public_skill_file_overlay_max_bytes: int = Field(default=262144)

@lru_cache(maxsize=1)
def get_settings() -> Settings:
    return Settings()
