"""Shared deadlines for governed tool-permission callbacks."""

TOOL_PERMISSION_WAIT_TIMEOUT_SECONDS = 900.0
TOOL_PERMISSION_CALLBACK_TRANSPORT_MARGIN_SECONDS = 15.0
TOOL_PERMISSION_CALLBACK_TRANSPORT_TIMEOUT_SECONDS = (
    TOOL_PERMISSION_WAIT_TIMEOUT_SECONDS + TOOL_PERMISSION_CALLBACK_TRANSPORT_MARGIN_SECONDS
)
