#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Export a compact paragraph map for outer agent semantic review."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Export compact review text from document_map.json.")
    parser.add_argument("document_map_json", help="Path to document_map.json generated by run_qa_review.py.")
    parser.add_argument("output_txt", help="Path to write compact agent review context.")
    parser.add_argument("--max-chars", type=int, default=240000, help="Maximum output characters.")
    return parser.parse_args()


def paragraph_label(item: dict[str, Any]) -> str:
    logical = item.get("logical_index") or item.get("xml_index") or "?"
    xml_index = item.get("xml_index") or "?"
    zone = item.get("document_zone") or "body"
    table = item.get("table_index")
    row = item.get("row_index")
    cell = item.get("cell_index")
    if table and row and cell:
        return f"P{logical} XML:{xml_index} zone:{zone} T{table}R{row}C{cell}"
    return f"P{logical} XML:{xml_index} zone:{zone}"


def main() -> int:
    args = parse_args()
    payload = json.loads(Path(args.document_map_json).read_text(encoding="utf-8-sig"))
    paragraphs = payload.get("paragraphs", [])
    if not isinstance(paragraphs, list):
        raise SystemExit("document_map.paragraphs must be a list")

    lines: list[str] = []
    total = 0
    for item in paragraphs:
        if not isinstance(item, dict):
            continue
        text = str(item.get("text") or "").strip()
        if not text:
            continue
        line = f"{paragraph_label(item)} | {text}"
        if total + len(line) + 1 > args.max_chars:
            lines.append("[TRUNCATED] Agent should inspect document_map.json directly for omitted paragraphs.")
            break
        lines.append(line)
        total += len(line) + 1

    output = Path(args.output_txt)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines) + ("\n" if lines else ""), encoding="utf-8")
    print(f"wrote {output} ({len(lines)} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
