#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Export compact review context and location indexes for outer agents."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

try:
    from review_units import build_bilingual_pairs, build_review_units, build_review_units_v2, format_context_line, write_jsonl
except ModuleNotFoundError:  # Support package-style imports in tests/tools.
    from .review_units import build_bilingual_pairs, build_review_units, build_review_units_v2, format_context_line, write_jsonl


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Export compact review text from document_map.json.")
    parser.add_argument("document_map_json", help="Path to document_map.json generated by run_qa_review.py.")
    parser.add_argument("output_txt", help="Path to write compact agent review context.")
    parser.add_argument("--max-chars", type=int, default=240000, help="Maximum output characters.")
    parser.add_argument("--context-version", choices=["v1", "v2"], default="v1", help="Agent review context format.")
    parser.add_argument("--max-chars-per-part", type=int, default=240000, help="Maximum characters per v2 context part.")
    parser.add_argument("--units-jsonl", default="", help="Path to write review_units.jsonl.")
    parser.add_argument("--bilingual-pairs-jsonl", default="", help="Path to write bilingual_pairs.jsonl.")
    return parser.parse_args()


def export_context(
    document_map_json: Path,
    output_txt: Path,
    *,
    max_chars: int = 240000,
    units_jsonl: Path | None = None,
    bilingual_pairs_jsonl: Path | None = None,
) -> tuple[int, int, Path, Path]:
    payload = json.loads(document_map_json.read_text(encoding="utf-8-sig"))
    units = build_review_units(payload)
    pairs = build_bilingual_pairs(units)

    output_txt.parent.mkdir(parents=True, exist_ok=True)
    units_path = units_jsonl or output_txt.with_name("review_units.jsonl")
    pairs_path = bilingual_pairs_jsonl or output_txt.with_name("bilingual_pairs.jsonl")

    write_jsonl(units_path, units)
    write_jsonl(pairs_path, pairs)

    lines: list[str] = []
    total = 0
    for unit in units:
        line = format_context_line(unit)
        if total + len(line) + 1 > max_chars:
            lines.append(
                "[TRUNCATED] Additional review units omitted by --max-chars; "
                "use JSONL sidecars only for locator verification."
            )
            break
        lines.append(line)
        total += len(line) + 1

    output_txt.write_text("\n".join(lines) + ("\n" if lines else ""), encoding="utf-8")
    return len(lines), len(pairs), units_path, pairs_path


def _format_context_v2_unit(unit: dict) -> str:
    same_cell = ",".join(unit.get("same_cell_unit_ids") or []) or "-"
    neighbors = ",".join(unit.get("neighbor_unit_ids") or []) or "-"
    review_domains = ", ".join(unit.get("review_domains") or []) or "-"
    section_path = unit.get("section_path") or []
    lines = [
        f"### UNIT {unit['unit_id']}",
        f"block_id: {unit.get('block_id') or '-'}",
        f"kind: {'table_cell' if unit.get('zone') == 'table' else 'body'}",
        f"text_kind: {unit.get('text_kind') or 'other'}",
        f"review_domains: {review_domains}",
    ]
    location_hint = unit.get("location_hint") or unit.get("zone") or ""
    if location_hint and location_hint != "body":
        lines.append(f"location_hint: {location_hint}")
    if unit.get("section_hint"):
        lines.append(f"section_hint: {unit.get('section_hint')}")
    if section_path:
        lines.append(f"section_path: {' > '.join(str(item) for item in section_path)}")
    lines.append(f"neighbors: {neighbors}")
    if same_cell != "-":
        lines.append(f"same_cell: {same_cell}")
    if unit.get("row_hint"):
        lines.append(f"row_hint: {unit.get('row_hint')}")
    if unit.get("col_hint"):
        lines.append(f"col_hint: {unit.get('col_hint')}")
    lines.extend(
        [
            "TEXT:",
            str(unit.get("text") or ""),
            "ANCHOR_RULE:",
            "anchor_quote must be copied from TEXT exactly. Do not use evidence text, replacement text, or generic labels.",
            "",
        ]
    )
    return "\n".join(lines)


def _block_kind(block_units: list[dict]) -> str:
    if any(unit.get("zone") == "table" for unit in block_units):
        return "table"
    if any("section_title" in (unit.get("review_domains") or []) for unit in block_units):
        return "section"
    return "body"


def _block_context_summary(block_kind: str, domains: list[str]) -> str:
    domain_text = ", ".join(domains) if domains else "language, data, formula, reference, ID, title, and semantic consistency"
    return (
        f"Review this {block_kind or 'block'} block for {domain_text}. "
        "The block is reading context only; report the UNIT containing the editable wrong phrase."
    )


def build_context_blocks_v21(units: list[dict]) -> list[dict]:
    blocks: list[dict] = []
    by_id: dict[str, dict] = {}
    units_by_block: dict[str, list[dict]] = {}

    for unit in units:
        block_id = str(unit.get("block_id") or "b-unknown")
        if block_id not in by_id:
            block = {
                "schema_version": "qa-review-context-block.v2.2",
                "block_id": block_id,
                "block_kind": "",
                "section_hint": unit.get("section_hint") or "",
                "review_domains": [],
                "unit_ids": [],
                "unit_count": 0,
                "locator_rule": "Choose the UNIT containing the editable wrong phrase. Evidence units only prove the issue.",
                "context_summary": "",
            }
            by_id[block_id] = block
            units_by_block[block_id] = []
            blocks.append(block)

        by_id[block_id]["unit_ids"].append(unit["unit_id"])
        units_by_block[block_id].append(unit)

    for block in blocks:
        block_units = units_by_block[block["block_id"]]
        domains = sorted({domain for unit in block_units for domain in (unit.get("review_domains") or [])})
        block["block_kind"] = _block_kind(block_units)
        block["review_domains"] = domains
        block["unit_count"] = len(block["unit_ids"])
        block["context_summary"] = _block_context_summary(block["block_kind"], domains)

    return blocks


def _context_v21_header(part_number: int, total_parts: int) -> str:
    return "\n".join(
        [
            "# QA Review Context v2.2",
            "# Scope: full-flow QA, not only bilingual comparison.",
            "# Review scope: Chinese, English, bilingual consistency, semantic consistency, tables, formulas, references, IDs, titles.",
            "# Problem locator: unit_id + anchor_quote copied from UNIT TEXT.",
            "# Required problem locator: unit_id + anchor_quote copied from UNIT TEXT.",
            "# Evidence locator: evidence_unit_ids may support the issue but are not insertion targets.",
            "# Hidden locators: do not expose P/XML/T/R/C hints in issue, evidence, or suggestion.",
            "",
            f"## PART {part_number:03d} / {total_parts:03d}",
            "",
        ]
    )


def _summarize_unit_ids(unit_ids: list, *, edge_count: int = 6) -> str:
    ids = [str(unit_id).strip() for unit_id in unit_ids if str(unit_id).strip()]
    if len(ids) <= edge_count * 2:
        return ",".join(ids)
    head = ",".join(ids[:edge_count])
    tail = ",".join(ids[-edge_count:])
    return f"{head},...,{tail} (unit_count={len(ids)})"


def _format_context_v21_block(block: dict) -> str:
    unit_ids = block.get("unit_ids") or []
    return "\n".join(
        [
            f"## BLOCK {block['block_id']}",
            f"block_kind: {block.get('block_kind') or '-'}",
            f"section_hint: {block.get('section_hint') or '-'}",
            f"review_domains: {', '.join(block.get('review_domains') or []) or '-'}",
            f"unit_count: {block.get('unit_count') or len(unit_ids)}",
            f"unit_ids: {_summarize_unit_ids(unit_ids)}",
            f"locator_rule: {block.get('locator_rule') or 'Choose the UNIT containing the editable wrong phrase.'}",
            f"context_summary: {block.get('context_summary') or 'Review language, data, formula, reference, ID, title, and semantic consistency proven by this block.'}",
            "",
        ]
    )


def render_context_v21(units: list[dict], blocks: list[dict], *, part_number: int, total_parts: int) -> str:
    chunks: list[str] = [_context_v21_header(part_number, total_parts)]

    block_by_id = {block["block_id"]: block for block in blocks}
    rendered_blocks: set[str] = set()

    for unit in units:
        block_id = str(unit.get("block_id") or "b-unknown")
        block = block_by_id.get(block_id)
        if block and block_id not in rendered_blocks:
            chunks.append(_format_context_v21_block(block))
            rendered_blocks.add(block_id)

        chunks.append(_format_context_v2_unit(unit))

    return "".join(chunks).rstrip() + "\n"


def _context_header(part_number: int, total_parts: int | None = None) -> str:
    total = "?" if total_parts is None else str(total_parts).zfill(3)
    return "\n".join(
        [
            "# QA Review Context v2",
            "# Return issues only when the exact editable source phrase appears inside one UNIT text.",
            "# Required locator fields: unit_id and anchor_quote.",
            "# Do not quote P/XML/T/R/C values in user-facing issue text.",
            "",
            f"## PART {str(part_number).zfill(3)} / {total}",
            "",
        ]
    )


def build_context_metrics(units: list[dict], blocks: list[dict], parts: list[list[dict]]) -> dict:
    domain_counts: dict[str, int] = {}
    for unit in units:
        for domain in unit.get("review_domains") or []:
            domain_counts[domain] = domain_counts.get(domain, 0) + 1

    return {
        "schema_version": "qa-review-context-metrics.v2.2",
        "unit_count": len(units),
        "block_count": len(blocks),
        "part_count": len(parts),
        "domain_counts": dict(sorted(domain_counts.items())),
        "table_unit_count": sum(1 for unit in units if unit.get("zone") == "table"),
        "body_unit_count": sum(1 for unit in units if unit.get("zone") != "table"),
        "short_anchor_risk_count": sum(
            1
            for unit in units
            if isinstance(unit.get("locator_safety"), dict)
            and unit["locator_safety"].get("short_anchor_risk")
        ),
    }


def export_context_v2(
    document_map_json: Path,
    output_txt: Path,
    *,
    max_chars_per_part: int = 240000,
) -> Path:
    payload = json.loads(document_map_json.read_text(encoding="utf-8-sig"))
    units = build_review_units_v2(payload)
    pairs = build_bilingual_pairs(units)
    blocks = build_context_blocks_v21(units)

    output_txt.parent.mkdir(parents=True, exist_ok=True)
    units_path = output_txt.with_name("review_units.jsonl")
    blocks_path = output_txt.with_name("review_blocks.jsonl")
    pairs_path = output_txt.with_name("bilingual_pairs.jsonl")
    metrics_path = output_txt.with_name("agent_context_metrics.json")
    manifest_path = output_txt.with_name("agent_context_manifest.json")

    block_by_id = {block["block_id"]: block for block in blocks}
    rendered_units = {unit["unit_id"]: _format_context_v2_unit(unit) for unit in units}
    rendered_blocks = {
        block_id: _format_context_v21_block(block)
        for block_id, block in block_by_id.items()
    }

    parts: list[list[dict]] = []
    current_part: list[dict] = []
    current_part_blocks: set[str] = set()
    current_size = len(_context_v21_header(1, 1))
    for unit in units:
        block_id = str(unit.get("block_id") or "b-unknown")
        block_text = rendered_blocks.get(block_id, "") if block_id not in current_part_blocks else ""
        unit_text = rendered_units[unit["unit_id"]]
        added_size = len(block_text) + len(unit_text)
        single_unit_size = len(rendered_blocks.get(block_id, "")) + len(unit_text)
        if single_unit_size > max_chars_per_part:
            raise ValueError(
                f"rendered unit {unit['unit_id']} exceeds --max-chars-per-part "
                f"({single_unit_size} > {max_chars_per_part})"
            )
        if current_part and current_size + added_size > max_chars_per_part:
            parts.append(current_part)
            current_part = []
            current_part_blocks = set()
            current_size = len(_context_v21_header(len(parts) + 1, 1))
            block_text = rendered_blocks.get(block_id, "")
            added_size = len(block_text) + len(unit_text)
        current_part.append(unit)
        current_part_blocks.add(block_id)
        current_size += added_size

    if current_part or not units:
        parts.append(current_part)

    part_names: list[str] = []
    total_parts = len(parts)
    for index, part_units in enumerate(parts, start=1):
        if total_parts == 1:
            part_path = output_txt
        else:
            part_path = output_txt.with_name(f"{output_txt.stem}.part-{index:03d}{output_txt.suffix}")
        part_path.write_text(render_context_v21(part_units, blocks, part_number=index, total_parts=total_parts), encoding="utf-8")
        part_names.append(part_path.name)

    write_jsonl(units_path, units)
    write_jsonl(blocks_path, blocks)
    write_jsonl(pairs_path, pairs)
    metrics = build_context_metrics(units, blocks, parts)
    metrics_path.write_text(json.dumps(metrics, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    manifest = {
        "schema_version": "qa-review-context-package.v2",
        "context_profile": "locator-v2.2",
        "document_map": document_map_json.name,
        "context_parts": part_names,
        "unit_index": units_path.name,
        "block_index": blocks_path.name,
        "bilingual_pairs": pairs_path.name,
        "metrics": metrics_path.name,
        "unit_count": len(units),
        "covered_unit_count": sum(len(part_units) for part_units in parts),
        "truncated": False,
    }
    manifest_path.write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    return manifest_path


def main() -> int:
    args = parse_args()
    output = Path(args.output_txt)
    if args.context_version == "v2":
        manifest_path = export_context_v2(
            Path(args.document_map_json),
            output,
            max_chars_per_part=args.max_chars_per_part,
        )
        print(f"wrote {manifest_path}")
        return 0

    line_count, pair_count, units_path, pairs_path = export_context(
        Path(args.document_map_json),
        output,
        max_chars=args.max_chars,
        units_jsonl=Path(args.units_jsonl) if args.units_jsonl else None,
        bilingual_pairs_jsonl=Path(args.bilingual_pairs_jsonl) if args.bilingual_pairs_jsonl else None,
    )
    print(f"wrote {output} ({line_count} lines)")
    print(f"wrote {units_path}")
    print(f"wrote {pairs_path} ({pair_count} pairs)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
