"""Application boundary for the Redis Stream-only runtime."""

from app.streaming.application.callback_events_v4 import (
    V4CallbackItem,
    callback_item_to_v4,
    callback_thinking_summary_to_v4,
)
from app.streaming.application.durable_v4 import (
    V4PublicationTransport,
    V4PublicationTransportUnavailable,
)
from app.streaming.application.worker_publication_v4 import (
    AssistantAnswerReceiptError,
    ReconstructedAssistantAnswer,
    WorkerV4Capabilities,
    admit_v4_stream,
    append_callback_v4_rows,
    publish_callback_rows,
    append_run_terminal_v4_row,
    finalize_parent_and_publish,
    persist_worker_event,
    publish_run_event,
)
from app.streaming.domain.live import (
    REDIS_ID_PATTERN,
    RUN_ID_PATTERN,
    STREAM_KEY_PREFIX,
    TENANT_SCOPE_PATTERN,
    StreamContractError,
    live_redis_id_is_after,
    redis_id_tuple,
    stream_key,
    tenant_scope,
)
from app.streaming.domain.public_events_v4 import (
    V4_METADATA_KEY as V4_METADATA_KEY,
    V4_METADATA_VERSION as V4_METADATA_VERSION,
    V4_PUBLIC_STAGE as V4_PUBLIC_STAGE,
    V4ProjectionError,
    V4StreamEntry,
    _APPLICATION_EVENT_TYPES as _APPLICATION_EVENT_TYPES,
    _MESSAGE_EVENT_TYPES as _MESSAGE_EVENT_TYPES,
    _RUN_DOMAIN_EVENT_TYPES as _RUN_DOMAIN_EVENT_TYPES,
    _nonempty as _nonempty,
    _safe_ref as _safe_ref,
    _stable_event_id as _stable_event_id,
    _stable_run_event_id as _stable_run_event_id,
    _validate_control_payload as _validate_control_payload,
    _validate_payload as _validate_payload,
    build_public_v4_control,
    build_v4_control,
    opaque_message_id,
    project_persisted_message_delta_v4,
    project_public_envelope_v4,
    project_public_v4,
    stream_end_event_id,
    validate_internal_envelope_v4,
    validate_public_application_payload_v4,
)
from app.streaming.domain.transport import (
    ResumeDecision,
    StreamCursor,
    StreamGap,
    canonical_json_bytes,
)


__all__ = [
    "REDIS_ID_PATTERN",
    "RUN_ID_PATTERN",
    "STREAM_KEY_PREFIX",
    "TENANT_SCOPE_PATTERN",
    "V4CallbackItem",
    "V4ProjectionError",
    "V4PublicationTransport",
    "V4PublicationTransportUnavailable",
    "V4StreamEntry",
    "AssistantAnswerReceiptError",
    "ReconstructedAssistantAnswer",
    "WorkerV4Capabilities",
    "admit_v4_stream",
    "append_callback_v4_rows",
    "publish_callback_rows",
    "append_run_terminal_v4_row",
    "build_public_v4_control",
    "build_v4_control",
    "callback_item_to_v4",
    "callback_thinking_summary_to_v4",
    "opaque_message_id",
    "project_persisted_message_delta_v4",
    "project_public_envelope_v4",
    "project_public_v4",
    "publish_run_event",
    "finalize_parent_and_publish",
    "persist_worker_event",
    "stream_end_event_id",
    "validate_internal_envelope_v4",
    "validate_public_application_payload_v4",
    "ResumeDecision",
    "StreamContractError",
    "StreamCursor",
    "StreamGap",
    "canonical_json_bytes",
    "live_redis_id_is_after",
    "redis_id_tuple",
    "stream_key",
    "tenant_scope",
]
