"""Stable SSE v3 application boundary."""

from app.streaming.application.callback_events_v4 import (
    V4CallbackItem,
    callback_item_to_v4,
    callback_thinking_summary_to_v4,
)
from app.streaming.application.durable_v4 import (
    V4PublicationClaim,
    V4PublicationClaims,
    V4PublicationTransport,
    V4PublicationTransportUnavailable,
    publish_claimed_v4_events,
    publish_due_v4_events,
)
from app.streaming.application.recovery_v4 import (
    V4ReadySuccessorRebuild,
    V4SuccessorActivation,
    V4SuccessorActivations,
    V4SuccessorRebuildClaim,
    V4SuccessorRebuildItem,
    V4SuccessorRebuildReceipt,
    V4SuccessorRebuildTransport,
    V4SuccessorRebuilds,
    activate_v4_successor_rebuild,
    build_v4_successor_rebuild,
    prepare_v4_successor_rebuild,
    recover_v4_missing_terminal_stream,
)
from app.streaming.application.live_fanout import (
    LiveSubscription,
    LiveSubscriptionClosed,
    RunStreamHub,
)
from app.streaming.application.worker_publication_v4 import (
    WorkerV4Capabilities,
    admit_v4_stream,
    append_callback_v4_rows,
    append_run_terminal_v4_row,
    finalize_parent_and_publish,
    persist_and_publish_worker_event,
    publish_pending_admissions,
    publish_pending_run_terminal,
    publish_pending_v4_events,
)
from app.streaming.domain.live import (
    REDIS_ID_PATTERN,
    RUN_ID_PATTERN,
    STREAM_KEY_PREFIX,
    TENANT_SCOPE_PATTERN,
    LiveEnvelope,
    LivePublication,
    StreamContractError,
    live_redis_id_is_after,
    redis_id_tuple,
    stream_key,
    stream_live_channel,
)
from app.streaming.domain.public_events_v4 import (
    V4_METADATA_KEY as V4_METADATA_KEY,
    V4_METADATA_VERSION as V4_METADATA_VERSION,
    V4_PUBLIC_STAGE as V4_PUBLIC_STAGE,
    V4ProjectionError,
    V4StreamEntry,
    _APPLICATION_EVENT_TYPES as _APPLICATION_EVENT_TYPES,
    _MESSAGE_EVENT_TYPES as _MESSAGE_EVENT_TYPES,
    _RUN_DOMAIN_EVENT_TYPES as _RUN_DOMAIN_EVENT_TYPES,
    _immutable_v4_payload as _immutable_v4_payload,
    _nonempty as _nonempty,
    _publication_state as _publication_state,
    _safe_ref as _safe_ref,
    _stable_event_id as _stable_event_id,
    _stable_run_event_id as _stable_run_event_id,
    _validate_control_payload as _validate_control_payload,
    _validate_payload as _validate_payload,
    build_public_v4_control,
    build_v4_control,
    opaque_message_id,
    project_persisted_message_delta_v4,
    project_public_envelope_v4,
    project_public_v4,
    project_public_v4_successor,
    stream_end_event_id,
    successor_stream_open_event_id,
    strip_internal_envelope as strip_internal_envelope,
    validate_internal_envelope_v4,
    validate_public_application_payload_v4,
)
from app.streaming.domain.transport import (
    STREAM_GAP_SCHEMA,
    ResumeDecision,
    StreamCursor,
    StreamGap,
    canonical_json_bytes,
)


__all__ = [
    "REDIS_ID_PATTERN",
    "RUN_ID_PATTERN",
    "STREAM_GAP_SCHEMA",
    "STREAM_KEY_PREFIX",
    "TENANT_SCOPE_PATTERN",
    "LiveEnvelope",
    "LivePublication",
    "LiveSubscription",
    "LiveSubscriptionClosed",
    "V4CallbackItem",
    "V4ProjectionError",
    "V4ReadySuccessorRebuild",
    "V4PublicationClaim",
    "V4SuccessorActivation",
    "V4SuccessorActivations",
    "V4PublicationClaims",
    "V4PublicationTransport",
    "V4PublicationTransportUnavailable",
    "V4StreamEntry",
    "V4SuccessorRebuildClaim",
    "V4SuccessorRebuildItem",
    "V4SuccessorRebuildReceipt",
    "V4SuccessorRebuildTransport",
    "V4SuccessorRebuilds",
    "WorkerV4Capabilities",
    "activate_v4_successor_rebuild",
    "admit_v4_stream",
    "append_callback_v4_rows",
    "append_run_terminal_v4_row",
    "build_public_v4_control",
    "build_v4_successor_rebuild",
    "build_v4_control",
    "callback_item_to_v4",
    "callback_thinking_summary_to_v4",
    "opaque_message_id",
    "project_persisted_message_delta_v4",
    "project_public_envelope_v4",
    "project_public_v4",
    "project_public_v4_successor",
    "publish_claimed_v4_events",
    "publish_due_v4_events",
    "publish_pending_admissions",
    "publish_pending_run_terminal",
    "publish_pending_v4_events",
    "finalize_parent_and_publish",
    "persist_and_publish_worker_event",
    "prepare_v4_successor_rebuild",
    "recover_v4_missing_terminal_stream",
    "stream_end_event_id",
    "successor_stream_open_event_id",
    "validate_internal_envelope_v4",
    "validate_public_application_payload_v4",
    "ResumeDecision",
    "RunStreamHub",
    "StreamContractError",
    "StreamCursor",
    "StreamGap",
    "canonical_json_bytes",
    "live_redis_id_is_after",
    "redis_id_tuple",
    "stream_key",
    "stream_live_channel",
]
