"""Stable SSE v3 application boundary."""

from app.streaming.application.live_fanout import (
    LiveSubscription,
    LiveSubscriptionClosed,
    RunStreamHub,
)
from app.streaming.domain.live import (
    REDIS_ID_PATTERN,
    RUN_ID_PATTERN,
    STREAM_KEY_PREFIX,
    TENANT_SCOPE_PATTERN,
    LiveEnvelope,
    LivePublication,
    StreamContractError,
    live_redis_id_is_after,
    redis_id_tuple,
    stream_key,
    stream_live_channel,
)
from app.streaming.domain.public_events_v4 import (
    V4_METADATA_KEY as V4_METADATA_KEY,
    V4_METADATA_VERSION as V4_METADATA_VERSION,
    V4_PUBLIC_STAGE as V4_PUBLIC_STAGE,
    V4ProjectionError,
    V4StreamEntry,
    _APPLICATION_EVENT_TYPES as _APPLICATION_EVENT_TYPES,
    _MESSAGE_EVENT_TYPES as _MESSAGE_EVENT_TYPES,
    _RUN_DOMAIN_EVENT_TYPES as _RUN_DOMAIN_EVENT_TYPES,
    _immutable_v4_payload as _immutable_v4_payload,
    _nonempty as _nonempty,
    _publication_state as _publication_state,
    _row_for_current_authority as _row_for_current_authority,
    _safe_ref as _safe_ref,
    _stable_event_id as _stable_event_id,
    _stable_run_event_id as _stable_run_event_id,
    _validate_control_payload as _validate_control_payload,
    _validate_payload as _validate_payload,
    build_public_v4_control,
    build_v4_control,
    opaque_message_id,
    project_public_envelope_v4,
    project_public_v4,
    stream_end_event_id,
    strip_internal_envelope as strip_internal_envelope,
    validate_internal_envelope_v4,
)
from app.streaming.domain.transport import (
    STREAM_GAP_SCHEMA,
    ResumeDecision,
    StreamCursor,
    StreamGap,
    canonical_json_bytes,
)


__all__ = [
    "REDIS_ID_PATTERN",
    "RUN_ID_PATTERN",
    "STREAM_GAP_SCHEMA",
    "STREAM_KEY_PREFIX",
    "TENANT_SCOPE_PATTERN",
    "LiveEnvelope",
    "LivePublication",
    "LiveSubscription",
    "LiveSubscriptionClosed",
    "V4ProjectionError",
    "V4StreamEntry",
    "build_public_v4_control",
    "build_v4_control",
    "opaque_message_id",
    "project_public_envelope_v4",
    "project_public_v4",
    "stream_end_event_id",
    "validate_internal_envelope_v4",
    "ResumeDecision",
    "RunStreamHub",
    "StreamContractError",
    "StreamCursor",
    "StreamGap",
    "canonical_json_bytes",
    "live_redis_id_is_after",
    "redis_id_tuple",
    "stream_key",
    "stream_live_channel",
]
