"""Generated by tools/generate_sse_v3_contracts.py; do not edit."""

from __future__ import annotations

from typing import Final, Literal, TypeAlias, TypedDict

from app.streaming.domain import protocol_v4 as _protocol_v4

INTERNAL_STREAM_EVENT_SCHEMA_V4: Final = _protocol_v4.INTERNAL_STREAM_EVENT_SCHEMA
PUBLIC_RUN_STREAM_SCHEMA_V4: Final = _protocol_v4.PUBLIC_RUN_STREAM_SCHEMA
PUBLIC_STREAM_EVENT_TYPES_V4: Final = _protocol_v4.PUBLIC_STREAM_EVENT_TYPES
STREAM_DESIGN_ID_V4: Final = _protocol_v4.STREAM_DESIGN_ID
STREAM_PROJECTION_VERSION_V4: Final = _protocol_v4.STREAM_PROJECTION_VERSION
PublicRunStreamEventV4: TypeAlias = _protocol_v4.PublicRunStreamEventV4

PUBLIC_RUN_STREAM_SCHEMA: Final = "ai-platform.public-run-stream-event.v3"
INTERNAL_STREAM_EVENT_SCHEMA: Final = "ai-platform.stream-event.v3"
STREAM_PROJECTION_VERSION: Final = "public-stream-v3"
STREAM_DESIGN_ID: Final = "ai-platform.redis-streams-sse-event-channel.v3"
PUBLIC_STREAM_EVENT_TYPES: Final = frozenset(
    (
        "stream_open",
        "assistant_text_delta",
        "semantic_stage",
        "semantic_progress",
        "terminal",
        "end",
    )
)

PUBLIC_APPLICATION_EVENT_TYPES_V4: Final = frozenset(
    value for value in PUBLIC_STREAM_EVENT_TYPES_V4
    if not value.startswith("stream.")
)


class StreamOpenEventV3Payload(TypedDict):
    design_id: Literal["ai-platform.redis-streams-sse-event-channel.v3"]


class AssistantTextDeltaEventV3Payload(TypedDict):
    delta: str


class SemanticStageEventV3Payload(TypedDict):
    event: Literal["run_event"]
    data: dict[str, object]


class SemanticProgressEventV3Payload(TypedDict):
    event: Literal["execution_progress", "execution_step", "execution_step_completed", "execution_step_failed"]
    data: dict[str, object]


class TerminalEventV3Payload(TypedDict):
    event_id: str
    hydrate_required: Literal[True]
    status: Literal["succeeded", "failed", "cancelled"]


class EndEventV3Payload(TypedDict):
    terminal_event_id: str


class EventIdentityV3(TypedDict):
    schema: Literal["ai-platform.public-run-stream-event.v3"]
    event_id: str
    run_id: str
    stream_incarnation: int
    emitted_at: str


class StreamOpenEventV3(TypedDict):
    schema: Literal["ai-platform.public-run-stream-event.v3"]
    event_id: str
    run_id: str
    stream_incarnation: int
    emitted_at: str
    event_type: Literal["stream_open"]
    payload: StreamOpenEventV3Payload


class AssistantTextDeltaEventV3(TypedDict):
    schema: Literal["ai-platform.public-run-stream-event.v3"]
    event_id: str
    run_id: str
    stream_incarnation: int
    emitted_at: str
    event_type: Literal["assistant_text_delta"]
    payload: AssistantTextDeltaEventV3Payload


class SemanticStageEventV3(TypedDict):
    schema: Literal["ai-platform.public-run-stream-event.v3"]
    event_id: str
    run_id: str
    stream_incarnation: int
    emitted_at: str
    event_type: Literal["semantic_stage"]
    payload: SemanticStageEventV3Payload


class SemanticProgressEventV3(TypedDict):
    schema: Literal["ai-platform.public-run-stream-event.v3"]
    event_id: str
    run_id: str
    stream_incarnation: int
    emitted_at: str
    event_type: Literal["semantic_progress"]
    payload: SemanticProgressEventV3Payload


class TerminalEventV3(TypedDict):
    schema: Literal["ai-platform.public-run-stream-event.v3"]
    event_id: str
    run_id: str
    stream_incarnation: int
    emitted_at: str
    event_type: Literal["terminal"]
    payload: TerminalEventV3Payload


class EndEventV3(TypedDict):
    schema: Literal["ai-platform.public-run-stream-event.v3"]
    event_id: str
    run_id: str
    stream_incarnation: int
    emitted_at: str
    event_type: Literal["end"]
    payload: EndEventV3Payload


PublicRunStreamEventV3: TypeAlias = StreamOpenEventV3 | AssistantTextDeltaEventV3 | SemanticStageEventV3 | SemanticProgressEventV3 | TerminalEventV3 | EndEventV3


class InternalStreamEnvelopeV3(TypedDict):
    schema: Literal["ai-platform.stream-event.v3"]
    event_id: str
    tenant_scope: str
    run_id: str
    attempt_id: str
    stream_incarnation: int
    event_type: Literal["stream_open", "assistant_text_delta", "semantic_stage", "semantic_progress", "terminal", "end"]
    emitted_at: str
    projection_version: Literal["public-stream-v3"]
    payload: dict[str, object]
