"""Generated by tools/generate_sse_v4_contracts.py; do not edit."""

from __future__ import annotations

from typing import Final, Literal, NotRequired, TypeAlias, TypedDict

PUBLIC_RUN_STREAM_SCHEMA: Final = "ai-platform.public-run-stream-event.v4"
INTERNAL_STREAM_EVENT_SCHEMA: Final = "ai-platform.stream-event.v4"
STREAM_PROJECTION_VERSION: Final = "public-stream-v4"
STREAM_DESIGN_ID: Final = "ai-platform.redis-streams-sse-event-channel.v4"
PUBLIC_STREAM_EVENT_TYPES: Final = frozenset(
    (
        "message.started",
        "message.delta",
        "message.completed",
        "thinking.started",
        "thinking.completed",
        "model.completed",
        "tool.started",
        "tool.completed",
        "tool.failed",
        "tool.denied",
        "subagent.started",
        "subagent.progress",
        "subagent.completed",
        "subagent.failed",
        "subagent.cancelled",
        "artifact.created",
        "artifact.ready",
        "artifact.failed",
        "policy.checking",
        "policy.allowed",
        "policy.denied",
        "run.cancel_requested",
        "run.succeeded",
        "run.cancelled",
        "run.failed",
        "stream.open",
        "stream.heartbeat",
        "stream.gap",
        "stream.end",
    )
)


class StreamOpenControlV4Payload(TypedDict):
    design_id: Literal["ai-platform.redis-streams-sse-event-channel.v4"]


class StreamHeartbeatControlV4Payload(TypedDict):
    status: Literal["queued", "running"]


class StreamGapControlV4Payload(TypedDict):
    reason: Literal["retained_history_unavailable", "stream_missing", "stream_continuity_unproven", "stream_incarnation_mismatch"]
    recovery: Literal["reload_durable_state"]
    requested_event_id: NullableSafeRefV4
    requested_stream_incarnation: int | None
    current_stream_incarnation: int
    earliest_available_event_id: NullableSafeRefV4
    latest_available_event_id: NullableSafeRefV4


class StreamEndControlV4Payload(TypedDict):
    terminal_event_id: SafeRefV4


class MessageDeltaEventV4Payload(TypedDict):
    delta: str


class MessageCompletedEventV4Payload(TypedDict):
    content: str


class ModelCompletedEventV4Payload(TypedDict):
    duration_ms: int
    turn_count: int
    stop_category: Literal["completed", "max_turns", "cancelled", "failed", "unknown"]


class ToolStartedEventV4Payload(TypedDict):
    operation_id: SafeRefV4
    category: ToolCategoryV4
    display_name: DisplayNameV4
    input_summary: NotRequired[str]
    evidence_refs: NotRequired[SafeRefArrayV4]


class ToolCompletedEventV4Payload(TypedDict):
    operation_id: SafeRefV4
    category: ToolCategoryV4
    display_name: DisplayNameV4
    duration_ms: int
    result_summary: NotRequired[str]
    evidence_refs: NotRequired[SafeRefArrayV4]
    artifact_refs: NotRequired[SafeRefArrayV4]


class ToolFailedEventV4Payload(TypedDict):
    operation_id: SafeRefV4
    category: ToolCategoryV4
    display_name: DisplayNameV4
    duration_ms: int
    failure_category: Literal["invalid_input", "not_found", "permission_denied", "timeout", "unavailable", "execution_failed"]
    evidence_refs: NotRequired[SafeRefArrayV4]


class ToolDeniedEventV4Payload(TypedDict):
    operation_id: SafeRefV4
    category: ToolCategoryV4
    display_name: DisplayNameV4
    denial_code: Literal["capability_not_authorized", "policy_denied"]


class SubagentStartedEventV4Payload(TypedDict):
    subagent_id: SafeRefV4
    display_name: DisplayNameV4


class SubagentProgressEventV4Payload(TypedDict):
    subagent_id: SafeRefV4
    display_name: DisplayNameV4
    duration_ms: int
    current_category: ToolCategoryV4
    progress_percent: NotRequired[int]


class SubagentCompletedEventV4Payload(TypedDict):
    subagent_id: SafeRefV4
    display_name: DisplayNameV4
    duration_ms: int


class SubagentFailedEventV4Payload(TypedDict):
    subagent_id: SafeRefV4
    display_name: DisplayNameV4
    duration_ms: int
    failure_category: Literal["subagent_failed"]


class SubagentCancelledEventV4Payload(TypedDict):
    subagent_id: SafeRefV4
    display_name: DisplayNameV4
    duration_ms: int
    reason_code: Literal["user_cancelled", "run_cancelled", "timeout"]


class ArtifactCreatedEventV4Payload(TypedDict):
    artifact_id: SafeRefV4
    filename: SafeFilenameV4
    media_type: str
    size_bytes: int
    status: Literal["created"]
    evidence_ref: NotRequired[NullableSafeRefV4]


class ArtifactReadyEventV4Payload(TypedDict):
    artifact_id: SafeRefV4
    filename: SafeFilenameV4
    media_type: str
    size_bytes: int
    status: Literal["ready"]
    evidence_ref: NotRequired[NullableSafeRefV4]


class ArtifactFailedEventV4Payload(TypedDict):
    artifact_id: SafeRefV4
    status: Literal["failed"]
    failure_category: Literal["artifact_failed", "unavailable"]
    filename: NotRequired[SafeFilenameV4]
    media_type: NotRequired[str]


class PolicyCheckingEventV4Payload(TypedDict):
    decision_id: SafeRefV4
    category: ToolCategoryV4
    display_name: DisplayNameV4


class PolicyAllowedEventV4Payload(TypedDict):
    decision_id: SafeRefV4
    category: ToolCategoryV4
    display_name: DisplayNameV4
    decision_code: Literal["allowed"]


class PolicyDeniedEventV4Payload(TypedDict):
    decision_id: SafeRefV4
    category: ToolCategoryV4
    display_name: DisplayNameV4
    decision_code: Literal["capability_not_authorized", "policy_denied"]


class RunCancelRequestedEventV4Payload(TypedDict):
    source: Literal["user", "system"]


class RunSucceededEventV4Payload(TypedDict):
    terminal_event_id: SafeRefV4
    hydrate_required: Literal[True]


class RunCancelledEventV4Payload(TypedDict):
    terminal_event_id: SafeRefV4
    hydrate_required: Literal[True]
    reason_code: Literal["user_cancelled", "policy_cancelled", "timeout"]


class RunFailedEventV4Payload(TypedDict):
    terminal_event_id: SafeRefV4
    hydrate_required: Literal[True]
    projection_version: Literal["ai-platform.chat-public-projection.v1"]
    code: str
    default_message: str
    detail: str | None


class PublicApplicationEnvelopeV4(TypedDict):
    schema: Literal["ai-platform.public-run-stream-event.v4"]
    event_id: EventIdV4
    run_id: RunIdV4
    message_id: NullableSafeRefV4
    seq: int
    event_type: Literal["message.started", "message.delta", "message.completed", "thinking.started", "thinking.completed", "model.completed", "tool.started", "tool.completed", "tool.failed", "tool.denied", "subagent.started", "subagent.progress", "subagent.completed", "subagent.failed", "subagent.cancelled", "artifact.created", "artifact.ready", "artifact.failed", "policy.checking", "policy.allowed", "policy.denied", "run.cancel_requested", "run.succeeded", "run.cancelled", "run.failed"]
    stream_incarnation: int
    replayable: Literal[True]
    trace_ref: NullableTraceRefV4
    causation_event_id: NullableSafeRefV4
    emitted_at: str
    payload: dict[str, object]


class PublicMessageApplicationEnvelopeV4(TypedDict):
    schema: Literal["ai-platform.public-run-stream-event.v4"]
    event_id: EventIdV4
    run_id: RunIdV4
    message_id: SafeRefV4
    seq: int
    event_type: Literal["message.started", "message.delta", "message.completed", "thinking.started", "thinking.completed", "model.completed", "tool.started", "tool.completed", "tool.failed", "tool.denied", "subagent.started", "subagent.progress", "subagent.completed", "subagent.failed", "subagent.cancelled", "artifact.created", "artifact.ready", "artifact.failed", "policy.checking", "policy.allowed", "policy.denied", "run.cancel_requested", "run.succeeded", "run.cancelled", "run.failed"]
    stream_incarnation: int
    replayable: Literal[True]
    trace_ref: NullableTraceRefV4
    causation_event_id: NullableSafeRefV4
    emitted_at: str
    payload: dict[str, object]


class PublicTransportControlEnvelopeV4(TypedDict):
    schema: Literal["ai-platform.public-run-stream-control.v4"]
    event_id: EventIdV4
    run_id: RunIdV4
    message_id: None
    seq: None
    event_type: Literal["stream.open", "stream.heartbeat", "stream.gap", "stream.end"]
    stream_incarnation: int
    replayable: bool
    trace_ref: None
    causation_event_id: NullableSafeRefV4
    emitted_at: str
    payload: dict[str, object]


class StreamOpenControlV4(TypedDict):
    schema: Literal["ai-platform.public-run-stream-control.v4"]
    event_id: EventIdV4
    run_id: RunIdV4
    message_id: None
    seq: None
    event_type: Literal["stream.open"]
    stream_incarnation: int
    replayable: Literal[True]
    trace_ref: None
    causation_event_id: NullableSafeRefV4
    emitted_at: str
    payload: StreamOpenControlV4Payload


class StreamHeartbeatControlV4(TypedDict):
    schema: Literal["ai-platform.public-run-stream-control.v4"]
    event_id: EventIdV4
    run_id: RunIdV4
    message_id: None
    seq: None
    event_type: Literal["stream.heartbeat"]
    stream_incarnation: int
    replayable: Literal[False]
    trace_ref: None
    causation_event_id: NullableSafeRefV4
    emitted_at: str
    payload: StreamHeartbeatControlV4Payload


class StreamGapControlV4(TypedDict):
    schema: Literal["ai-platform.public-run-stream-control.v4"]
    event_id: EventIdV4
    run_id: RunIdV4
    message_id: None
    seq: None
    event_type: Literal["stream.gap"]
    stream_incarnation: int
    replayable: Literal[False]
    trace_ref: None
    causation_event_id: NullableSafeRefV4
    emitted_at: str
    payload: StreamGapControlV4Payload


class StreamEndControlV4(TypedDict):
    schema: Literal["ai-platform.public-run-stream-control.v4"]
    event_id: EventIdV4
    run_id: RunIdV4
    message_id: None
    seq: None
    event_type: Literal["stream.end"]
    stream_incarnation: int
    replayable: Literal[True]
    trace_ref: None
    causation_event_id: NullableSafeRefV4
    emitted_at: str
    payload: StreamEndControlV4Payload


class MessageStartedEventV4(TypedDict):
    schema: Literal["ai-platform.public-run-stream-event.v4"]
    event_id: EventIdV4
    run_id: RunIdV4
    message_id: SafeRefV4
    seq: int
    event_type: Literal["message.started"]
    stream_incarnation: int
    replayable: Literal[True]
    trace_ref: NullableTraceRefV4
    causation_event_id: NullableSafeRefV4
    emitted_at: str
    payload: EmptyPayloadV4


class MessageDeltaEventV4(TypedDict):
    schema: Literal["ai-platform.public-run-stream-event.v4"]
    event_id: EventIdV4
    run_id: RunIdV4
    message_id: SafeRefV4
    seq: int
    event_type: Literal["message.delta"]
    stream_incarnation: int
    replayable: Literal[True]
    trace_ref: NullableTraceRefV4
    causation_event_id: NullableSafeRefV4
    emitted_at: str
    payload: MessageDeltaEventV4Payload


class MessageCompletedEventV4(TypedDict):
    schema: Literal["ai-platform.public-run-stream-event.v4"]
    event_id: EventIdV4
    run_id: RunIdV4
    message_id: SafeRefV4
    seq: int
    event_type: Literal["message.completed"]
    stream_incarnation: int
    replayable: Literal[True]
    trace_ref: NullableTraceRefV4
    causation_event_id: NullableSafeRefV4
    emitted_at: str
    payload: MessageCompletedEventV4Payload


class ThinkingStartedEventV4(TypedDict):
    schema: Literal["ai-platform.public-run-stream-event.v4"]
    event_id: EventIdV4
    run_id: RunIdV4
    message_id: SafeRefV4
    seq: int
    event_type: Literal["thinking.started"]
    stream_incarnation: int
    replayable: Literal[True]
    trace_ref: NullableTraceRefV4
    causation_event_id: NullableSafeRefV4
    emitted_at: str
    payload: EmptyPayloadV4


class ThinkingCompletedEventV4(TypedDict):
    schema: Literal["ai-platform.public-run-stream-event.v4"]
    event_id: EventIdV4
    run_id: RunIdV4
    message_id: SafeRefV4
    seq: int
    event_type: Literal["thinking.completed"]
    stream_incarnation: int
    replayable: Literal[True]
    trace_ref: NullableTraceRefV4
    causation_event_id: NullableSafeRefV4
    emitted_at: str
    payload: EmptyPayloadV4


class ModelCompletedEventV4(TypedDict):
    schema: Literal["ai-platform.public-run-stream-event.v4"]
    event_id: EventIdV4
    run_id: RunIdV4
    message_id: SafeRefV4
    seq: int
    event_type: Literal["model.completed"]
    stream_incarnation: int
    replayable: Literal[True]
    trace_ref: NullableTraceRefV4
    causation_event_id: NullableSafeRefV4
    emitted_at: str
    payload: ModelCompletedEventV4Payload


class ToolStartedEventV4(TypedDict):
    schema: Literal["ai-platform.public-run-stream-event.v4"]
    event_id: EventIdV4
    run_id: RunIdV4
    message_id: SafeRefV4
    seq: int
    event_type: Literal["tool.started"]
    stream_incarnation: int
    replayable: Literal[True]
    trace_ref: NullableTraceRefV4
    causation_event_id: NullableSafeRefV4
    emitted_at: str
    payload: ToolStartedEventV4Payload


class ToolCompletedEventV4(TypedDict):
    schema: Literal["ai-platform.public-run-stream-event.v4"]
    event_id: EventIdV4
    run_id: RunIdV4
    message_id: SafeRefV4
    seq: int
    event_type: Literal["tool.completed"]
    stream_incarnation: int
    replayable: Literal[True]
    trace_ref: NullableTraceRefV4
    causation_event_id: NullableSafeRefV4
    emitted_at: str
    payload: ToolCompletedEventV4Payload


class ToolFailedEventV4(TypedDict):
    schema: Literal["ai-platform.public-run-stream-event.v4"]
    event_id: EventIdV4
    run_id: RunIdV4
    message_id: SafeRefV4
    seq: int
    event_type: Literal["tool.failed"]
    stream_incarnation: int
    replayable: Literal[True]
    trace_ref: NullableTraceRefV4
    causation_event_id: NullableSafeRefV4
    emitted_at: str
    payload: ToolFailedEventV4Payload


class ToolDeniedEventV4(TypedDict):
    schema: Literal["ai-platform.public-run-stream-event.v4"]
    event_id: EventIdV4
    run_id: RunIdV4
    message_id: SafeRefV4
    seq: int
    event_type: Literal["tool.denied"]
    stream_incarnation: int
    replayable: Literal[True]
    trace_ref: NullableTraceRefV4
    causation_event_id: NullableSafeRefV4
    emitted_at: str
    payload: ToolDeniedEventV4Payload


class SubagentStartedEventV4(TypedDict):
    schema: Literal["ai-platform.public-run-stream-event.v4"]
    event_id: EventIdV4
    run_id: RunIdV4
    message_id: SafeRefV4
    seq: int
    event_type: Literal["subagent.started"]
    stream_incarnation: int
    replayable: Literal[True]
    trace_ref: NullableTraceRefV4
    causation_event_id: NullableSafeRefV4
    emitted_at: str
    payload: SubagentStartedEventV4Payload


class SubagentProgressEventV4(TypedDict):
    schema: Literal["ai-platform.public-run-stream-event.v4"]
    event_id: EventIdV4
    run_id: RunIdV4
    message_id: SafeRefV4
    seq: int
    event_type: Literal["subagent.progress"]
    stream_incarnation: int
    replayable: Literal[True]
    trace_ref: NullableTraceRefV4
    causation_event_id: NullableSafeRefV4
    emitted_at: str
    payload: SubagentProgressEventV4Payload


class SubagentCompletedEventV4(TypedDict):
    schema: Literal["ai-platform.public-run-stream-event.v4"]
    event_id: EventIdV4
    run_id: RunIdV4
    message_id: SafeRefV4
    seq: int
    event_type: Literal["subagent.completed"]
    stream_incarnation: int
    replayable: Literal[True]
    trace_ref: NullableTraceRefV4
    causation_event_id: NullableSafeRefV4
    emitted_at: str
    payload: SubagentCompletedEventV4Payload


class SubagentFailedEventV4(TypedDict):
    schema: Literal["ai-platform.public-run-stream-event.v4"]
    event_id: EventIdV4
    run_id: RunIdV4
    message_id: SafeRefV4
    seq: int
    event_type: Literal["subagent.failed"]
    stream_incarnation: int
    replayable: Literal[True]
    trace_ref: NullableTraceRefV4
    causation_event_id: NullableSafeRefV4
    emitted_at: str
    payload: SubagentFailedEventV4Payload


class SubagentCancelledEventV4(TypedDict):
    schema: Literal["ai-platform.public-run-stream-event.v4"]
    event_id: EventIdV4
    run_id: RunIdV4
    message_id: SafeRefV4
    seq: int
    event_type: Literal["subagent.cancelled"]
    stream_incarnation: int
    replayable: Literal[True]
    trace_ref: NullableTraceRefV4
    causation_event_id: NullableSafeRefV4
    emitted_at: str
    payload: SubagentCancelledEventV4Payload


class ArtifactCreatedEventV4(TypedDict):
    schema: Literal["ai-platform.public-run-stream-event.v4"]
    event_id: EventIdV4
    run_id: RunIdV4
    message_id: NullableSafeRefV4
    seq: int
    event_type: Literal["artifact.created"]
    stream_incarnation: int
    replayable: Literal[True]
    trace_ref: NullableTraceRefV4
    causation_event_id: NullableSafeRefV4
    emitted_at: str
    payload: ArtifactCreatedEventV4Payload


class ArtifactReadyEventV4(TypedDict):
    schema: Literal["ai-platform.public-run-stream-event.v4"]
    event_id: EventIdV4
    run_id: RunIdV4
    message_id: NullableSafeRefV4
    seq: int
    event_type: Literal["artifact.ready"]
    stream_incarnation: int
    replayable: Literal[True]
    trace_ref: NullableTraceRefV4
    causation_event_id: NullableSafeRefV4
    emitted_at: str
    payload: ArtifactReadyEventV4Payload


class ArtifactFailedEventV4(TypedDict):
    schema: Literal["ai-platform.public-run-stream-event.v4"]
    event_id: EventIdV4
    run_id: RunIdV4
    message_id: NullableSafeRefV4
    seq: int
    event_type: Literal["artifact.failed"]
    stream_incarnation: int
    replayable: Literal[True]
    trace_ref: NullableTraceRefV4
    causation_event_id: NullableSafeRefV4
    emitted_at: str
    payload: ArtifactFailedEventV4Payload


class PolicyCheckingEventV4(TypedDict):
    schema: Literal["ai-platform.public-run-stream-event.v4"]
    event_id: EventIdV4
    run_id: RunIdV4
    message_id: NullableSafeRefV4
    seq: int
    event_type: Literal["policy.checking"]
    stream_incarnation: int
    replayable: Literal[True]
    trace_ref: NullableTraceRefV4
    causation_event_id: NullableSafeRefV4
    emitted_at: str
    payload: PolicyCheckingEventV4Payload


class PolicyAllowedEventV4(TypedDict):
    schema: Literal["ai-platform.public-run-stream-event.v4"]
    event_id: EventIdV4
    run_id: RunIdV4
    message_id: NullableSafeRefV4
    seq: int
    event_type: Literal["policy.allowed"]
    stream_incarnation: int
    replayable: Literal[True]
    trace_ref: NullableTraceRefV4
    causation_event_id: NullableSafeRefV4
    emitted_at: str
    payload: PolicyAllowedEventV4Payload


class PolicyDeniedEventV4(TypedDict):
    schema: Literal["ai-platform.public-run-stream-event.v4"]
    event_id: EventIdV4
    run_id: RunIdV4
    message_id: NullableSafeRefV4
    seq: int
    event_type: Literal["policy.denied"]
    stream_incarnation: int
    replayable: Literal[True]
    trace_ref: NullableTraceRefV4
    causation_event_id: NullableSafeRefV4
    emitted_at: str
    payload: PolicyDeniedEventV4Payload


class RunCancelRequestedEventV4(TypedDict):
    schema: Literal["ai-platform.public-run-stream-event.v4"]
    event_id: EventIdV4
    run_id: RunIdV4
    message_id: NullableSafeRefV4
    seq: int
    event_type: Literal["run.cancel_requested"]
    stream_incarnation: int
    replayable: Literal[True]
    trace_ref: NullableTraceRefV4
    causation_event_id: NullableSafeRefV4
    emitted_at: str
    payload: RunCancelRequestedEventV4Payload


class RunSucceededEventV4(TypedDict):
    schema: Literal["ai-platform.public-run-stream-event.v4"]
    event_id: EventIdV4
    run_id: RunIdV4
    message_id: NullableSafeRefV4
    seq: int
    event_type: Literal["run.succeeded"]
    stream_incarnation: int
    replayable: Literal[True]
    trace_ref: NullableTraceRefV4
    causation_event_id: NullableSafeRefV4
    emitted_at: str
    payload: RunSucceededEventV4Payload


class RunCancelledEventV4(TypedDict):
    schema: Literal["ai-platform.public-run-stream-event.v4"]
    event_id: EventIdV4
    run_id: RunIdV4
    message_id: NullableSafeRefV4
    seq: int
    event_type: Literal["run.cancelled"]
    stream_incarnation: int
    replayable: Literal[True]
    trace_ref: NullableTraceRefV4
    causation_event_id: NullableSafeRefV4
    emitted_at: str
    payload: RunCancelledEventV4Payload


class RunFailedEventV4(TypedDict):
    schema: Literal["ai-platform.public-run-stream-event.v4"]
    event_id: EventIdV4
    run_id: RunIdV4
    message_id: NullableSafeRefV4
    seq: int
    event_type: Literal["run.failed"]
    stream_incarnation: int
    replayable: Literal[True]
    trace_ref: NullableTraceRefV4
    causation_event_id: NullableSafeRefV4
    emitted_at: str
    payload: RunFailedEventV4Payload


class RunEventSourceV4(TypedDict):
    kind: Literal["run_event"]
    run_event_id: SafeRefV4
    sequence: int


class StreamAuthoritySourceV4(TypedDict):
    kind: Literal["stream_authority"]
    authority_id: SafeRefV4


class TerminalIntentSourceV4(TypedDict):
    kind: Literal["terminal_intent"]
    terminal_event_id: SafeRefV4


NullableSafeRefV4: TypeAlias = SafeRefV4 | None


NullableTraceRefV4: TypeAlias = TraceRefV4 | None


PublicApplicationEventV4: TypeAlias = MessageStartedEventV4 | MessageDeltaEventV4 | MessageCompletedEventV4 | ThinkingStartedEventV4 | ThinkingCompletedEventV4 | ModelCompletedEventV4 | ToolStartedEventV4 | ToolCompletedEventV4 | ToolFailedEventV4 | ToolDeniedEventV4 | SubagentStartedEventV4 | SubagentProgressEventV4 | SubagentCompletedEventV4 | SubagentFailedEventV4 | SubagentCancelledEventV4 | ArtifactCreatedEventV4 | ArtifactReadyEventV4 | ArtifactFailedEventV4 | PolicyCheckingEventV4 | PolicyAllowedEventV4 | PolicyDeniedEventV4 | RunCancelRequestedEventV4 | RunSucceededEventV4 | RunCancelledEventV4 | RunFailedEventV4


PublicTransportControlEventV4: TypeAlias = StreamOpenControlV4 | StreamHeartbeatControlV4 | StreamGapControlV4 | StreamEndControlV4


PublicRunStreamEventV4: TypeAlias = PublicApplicationEventV4 | PublicTransportControlEventV4


class InternalStreamEnvelopeV4(TypedDict):
    schema: Literal["ai-platform.stream-event.v4"]
    event_id: EventIdV4
    tenant_scope: str
    run_id: RunIdV4
    attempt_id: AttemptIdV4
    message_id: NullableSafeRefV4
    seq: int | None
    event_type: Literal["message.started", "message.delta", "message.completed", "thinking.started", "thinking.completed", "model.completed", "tool.started", "tool.completed", "tool.failed", "tool.denied", "subagent.started", "subagent.progress", "subagent.completed", "subagent.failed", "subagent.cancelled", "artifact.created", "artifact.ready", "artifact.failed", "policy.checking", "policy.allowed", "policy.denied", "run.cancel_requested", "run.succeeded", "run.cancelled", "run.failed", "stream.open", "stream.heartbeat", "stream.gap", "stream.end"]
    stream_incarnation: int
    replayable: bool
    trace_ref: NullableTraceRefV4
    causation_event_id: NullableSafeRefV4
    emitted_at: str
    projection_version: Literal["public-stream-v4"]
    payload: dict[str, object]
    source: RunEventSourceV4 | StreamAuthoritySourceV4 | TerminalIntentSourceV4
