#!/usr/bin/env python3
"""Generate the SSE v3 Python and TypeScript contracts from one JSON Schema."""

from __future__ import annotations

import argparse
import json
import sys
from collections.abc import Mapping
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
SCHEMA_PATH = ROOT / "schemas" / "public_run_stream.v3.schema.json"
PYTHON_PATH = ROOT / "app" / "streaming" / "events.py"
TYPESCRIPT_PATH = (
    ROOT / "frontend" / "web" / "src" / "generated" / "publicRunStreamV3.ts"
)
GENERATED_HEADER = "Generated by tools/generate_sse_v3_contracts.py; do not edit."


def _load_schema() -> dict[str, Any]:
    value = json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))
    if not isinstance(value, dict) or not isinstance(value.get("$defs"), dict):
        raise ValueError("sse_v3_schema_invalid")
    return value


def _ref_name(node: Mapping[str, Any]) -> str | None:
    value = node.get("$ref")
    prefix = "#/$defs/"
    if isinstance(value, str) and value.startswith(prefix):
        return value[len(prefix) :]
    return None


def _merge_object(
    node: Mapping[str, Any], definitions: Mapping[str, Any]
) -> tuple[dict[str, Any], set[str]]:
    properties: dict[str, Any] = {}
    required: set[str] = set()
    reference = _ref_name(node)
    if reference is not None:
        target = definitions.get(reference)
        if not isinstance(target, Mapping):
            raise ValueError(f"sse_v3_schema_ref_invalid:{reference}")
        return _merge_object(target, definitions)
    for member in node.get("allOf", []):
        if not isinstance(member, Mapping):
            raise ValueError("sse_v3_schema_allof_invalid")
        nested_properties, nested_required = _merge_object(member, definitions)
        properties.update(nested_properties)
        required.update(nested_required)
    own_properties = node.get("properties", {})
    if not isinstance(own_properties, Mapping):
        raise ValueError("sse_v3_schema_properties_invalid")
    properties.update(own_properties)
    own_required = node.get("required", [])
    if not isinstance(own_required, list) or not all(
        isinstance(item, str) for item in own_required
    ):
        raise ValueError("sse_v3_schema_required_invalid")
    required.update(own_required)
    return properties, required


def _literal(value: object, *, typescript: bool) -> str:
    if value is True:
        return "true" if typescript else "Literal[True]"
    if value is False:
        return "false" if typescript else "Literal[False]"
    if value is None:
        return "null" if typescript else "None"
    if isinstance(value, str):
        quoted = json.dumps(value, ensure_ascii=False)
        return quoted if typescript else f"Literal[{quoted}]"
    if isinstance(value, (int, float)) and not isinstance(value, bool):
        return repr(value) if typescript else f"Literal[{value!r}]"
    raise ValueError("sse_v3_schema_literal_invalid")


def _python_type(node: Mapping[str, Any], definitions: Mapping[str, Any]) -> str:
    reference = _ref_name(node)
    if reference is not None:
        return reference
    if "const" in node:
        return _literal(node["const"], typescript=False)
    enum = node.get("enum")
    if isinstance(enum, list) and enum:
        values = ", ".join(json.dumps(value, ensure_ascii=False) for value in enum)
        return f"Literal[{values}]"
    one_of = node.get("oneOf")
    if isinstance(one_of, list) and one_of:
        return " | ".join(_python_type(member, definitions) for member in one_of)
    node_type = node.get("type")
    if node_type == "string":
        return "str"
    if node_type == "integer":
        return "int"
    if node_type == "number":
        return "float"
    if node_type == "boolean":
        return "bool"
    if node_type == "array":
        items = node.get("items", {})
        return f"list[{_python_type(items, definitions)}]"
    if node_type == "object" or "properties" in node or "allOf" in node:
        return "dict[str, object]"
    raise ValueError(f"sse_v3_schema_python_type_unsupported:{node}")


def _typescript_type(node: Mapping[str, Any], definitions: Mapping[str, Any]) -> str:
    reference = _ref_name(node)
    if reference is not None:
        return reference
    if "const" in node:
        return _literal(node["const"], typescript=True)
    enum = node.get("enum")
    if isinstance(enum, list) and enum:
        return " | ".join(_literal(value, typescript=True) for value in enum)
    one_of = node.get("oneOf")
    if isinstance(one_of, list) and one_of:
        return " | ".join(_typescript_type(member, definitions) for member in one_of)
    all_of = node.get("allOf")
    if isinstance(all_of, list) and all_of:
        return " & ".join(_typescript_type(member, definitions) for member in all_of)
    node_type = node.get("type")
    if node_type == "string":
        return "string"
    if node_type in {"integer", "number"}:
        return "number"
    if node_type == "boolean":
        return "boolean"
    if node_type == "array":
        items = node.get("items", {})
        return f"Array<{_typescript_type(items, definitions)}>"
    if node_type == "object" or "properties" in node:
        properties = node.get("properties", {})
        required = set(node.get("required", []))
        if not properties:
            return "Record<string, unknown>"
        lines = ["{"]
        for name, member in properties.items():
            marker = "" if name in required else "?"
            lines.append(
                f"  {json.dumps(name)}{marker}: {_typescript_type(member, definitions)};"
            )
        if node.get("additionalProperties") not in {False, None}:
            lines.append("  [key: string]: unknown;")
        lines.append("}")
        return "\n".join(lines)
    raise ValueError(f"sse_v3_schema_typescript_type_unsupported:{node}")


def _constants(schema: Mapping[str, Any]) -> dict[str, object]:
    definitions = schema["$defs"]
    identity = definitions["EventIdentityV3"]["properties"]
    internal = definitions["InternalStreamEnvelopeV3"]["properties"]
    event_types = internal["event_type"]["enum"]
    if not isinstance(event_types, list) or not all(
        isinstance(value, str) for value in event_types
    ):
        raise ValueError("sse_v3_event_types_invalid")
    return {
        "public_schema": identity["schema"]["const"],
        "internal_schema": internal["schema"]["const"],
        "projection_version": internal["projection_version"]["const"],
        "design_id": definitions["StreamOpenEventV3"]["allOf"][1]["properties"][
            "payload"
        ]["properties"]["design_id"]["const"],
        "event_types": tuple(event_types),
    }


def _render_python(schema: Mapping[str, Any]) -> str:
    definitions: Mapping[str, Any] = schema["$defs"]
    constants = _constants(schema)
    event_types = constants["event_types"]
    has_optional = False
    for definition in definitions.values():
        if not isinstance(definition, Mapping):
            continue
        properties, required = _merge_object(definition, definitions)
        has_optional = has_optional or any(name not in required for name in properties)
        for field_schema in properties.values():
            if isinstance(field_schema, Mapping) and field_schema.get("type") == "object":
                nested = field_schema.get("properties", {})
                nested_required = set(field_schema.get("required", []))
                has_optional = has_optional or any(
                    name not in nested_required for name in nested
                )
    typing_names = ["Final", "Literal"]
    if has_optional:
        typing_names.append("NotRequired")
    typing_names.extend(["TypeAlias", "TypedDict"])
    lines = [
        f'"""{GENERATED_HEADER}"""',
        "",
        "from __future__ import annotations",
        "",
        f"from typing import {', '.join(typing_names)}",
        "",
        "from app.streaming.domain import protocol_v4 as _protocol_v4",
        "",
        "INTERNAL_STREAM_EVENT_SCHEMA_V4: Final = _protocol_v4.INTERNAL_STREAM_EVENT_SCHEMA",
        "PUBLIC_RUN_STREAM_SCHEMA_V4: Final = _protocol_v4.PUBLIC_RUN_STREAM_SCHEMA",
        "PUBLIC_STREAM_EVENT_TYPES_V4: Final = _protocol_v4.PUBLIC_STREAM_EVENT_TYPES",
        "STREAM_DESIGN_ID_V4: Final = _protocol_v4.STREAM_DESIGN_ID",
        "STREAM_PROJECTION_VERSION_V4: Final = _protocol_v4.STREAM_PROJECTION_VERSION",
        "PublicRunStreamEventV4: TypeAlias = _protocol_v4.PublicRunStreamEventV4",
        "",
        f'PUBLIC_RUN_STREAM_SCHEMA: Final = {json.dumps(constants["public_schema"])}',
        f'INTERNAL_STREAM_EVENT_SCHEMA: Final = {json.dumps(constants["internal_schema"])}',
        f'STREAM_PROJECTION_VERSION: Final = {json.dumps(constants["projection_version"])}',
        f'STREAM_DESIGN_ID: Final = {json.dumps(constants["design_id"])}',
        "PUBLIC_STREAM_EVENT_TYPES: Final = frozenset(",
        "    (",
        *(f"        {json.dumps(value)}," for value in event_types),
        "    )",
        ")",
        "",
        "PUBLIC_APPLICATION_EVENT_TYPES_V4: Final = frozenset(",
        "    value for value in PUBLIC_STREAM_EVENT_TYPES_V4",
        '    if not value.startswith("stream.")',
        ")",
        "",
        "",
    ]
    synthetic_names: dict[tuple[str, str], str] = {}
    for definition_name, definition in definitions.items():
        if not isinstance(definition, Mapping):
            raise ValueError(f"sse_v3_definition_invalid:{definition_name}")
        properties, _ = _merge_object(definition, definitions)
        for field_name, field_schema in properties.items():
            if (
                isinstance(field_schema, Mapping)
                and field_schema.get("type") == "object"
                and field_schema.get("properties")
            ):
                synthetic_names[(definition_name, field_name)] = (
                    f"{definition_name}{field_name.title()}"
                )
    for (definition_name, field_name), synthetic_name in synthetic_names.items():
        definition = definitions[definition_name]
        properties, _ = _merge_object(definition, definitions)
        field_schema = properties[field_name]
        nested_properties = field_schema["properties"]
        nested_required = set(field_schema.get("required", []))
        lines.append(f"class {synthetic_name}(TypedDict):")
        for nested_name, nested_schema in nested_properties.items():
            nested_type = _python_type(nested_schema, definitions)
            if nested_name not in nested_required:
                nested_type = f"NotRequired[{nested_type}]"
            lines.append(f"    {nested_name}: {nested_type}")
        lines.extend(["", ""])
    aliases: list[tuple[str, Mapping[str, Any]]] = []
    internal_definition = definitions.get("InternalStreamEnvelopeV3")
    if not isinstance(internal_definition, Mapping):
        raise ValueError("sse_v3_internal_definition_invalid")
    for name, definition in definitions.items():
        if not isinstance(definition, Mapping):
            raise ValueError(f"sse_v3_definition_invalid:{name}")
        if name == "InternalStreamEnvelopeV3":
            continue
        if "oneOf" in definition:
            aliases.append((name, definition))
            continue
        properties, required = _merge_object(definition, definitions)
        if not properties:
            continue
        lines.append(f"class {name}(TypedDict):")
        for field_name, field_schema in properties.items():
            field_type = synthetic_names.get(
                (name, field_name), _python_type(field_schema, definitions)
            )
            if field_name not in required:
                field_type = f"NotRequired[{field_type}]"
            lines.append(f"    {field_name}: {field_type}")
        lines.extend(["", ""])
    for name, definition in aliases:
        lines.append(
            f"{name}: TypeAlias = {_python_type(definition, definitions)}"
        )
        lines.extend(["", ""])
    internal_properties, internal_required = _merge_object(
        internal_definition, definitions
    )
    lines.append("class InternalStreamEnvelopeV3(TypedDict):")
    for field_name, field_schema in internal_properties.items():
        field_type = synthetic_names.get(
            ("InternalStreamEnvelopeV3", field_name),
            _python_type(field_schema, definitions),
        )
        if field_name not in internal_required:
            field_type = f"NotRequired[{field_type}]"
        lines.append(f"    {field_name}: {field_type}")
    lines.append("")
    return "\n".join(lines)


def _render_typescript(schema: Mapping[str, Any]) -> str:
    definitions: Mapping[str, Any] = schema["$defs"]
    constants = _constants(schema)
    lines = [
        f"// {GENERATED_HEADER}",
        "",
        f'export const PUBLIC_RUN_STREAM_SCHEMA = {json.dumps(constants["public_schema"])} as const;',
        f'export const STREAM_PROJECTION_VERSION = {json.dumps(constants["projection_version"])} as const;',
        f'export const STREAM_DESIGN_ID = {json.dumps(constants["design_id"])} as const;',
        "export const PUBLIC_STREAM_EVENT_TYPES = [",
    ]
    lines.extend(
        f"  {json.dumps(value)}," for value in constants["event_types"]
    )
    lines.extend(["] as const;", ""])
    public_names = {
        "EventIdentityV3",
        "StreamOpenEventV3",
        "AssistantTextDeltaEventV3",
        "SemanticStageEventV3",
        "SemanticProgressEventV3",
        "TerminalEventV3",
        "EndEventV3",
        "PublicRunStreamEventV3",
    }
    for name, definition in definitions.items():
        if name not in public_names:
            continue
        if not isinstance(definition, Mapping):
            raise ValueError(f"sse_v3_definition_invalid:{name}")
        value = _typescript_type(definition, definitions)
        lines.append(f"export type {name} = {value};")
        lines.append("")
    return "\n".join(lines)


def _write_or_check(path: Path, expected: str, *, check: bool) -> bool:
    expected = expected.rstrip() + "\n"
    if check:
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current != expected:
            print(f"generated contract drift: {path.relative_to(ROOT)}", file=sys.stderr)
            return False
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(expected, encoding="utf-8", newline="\n")
    print(path.relative_to(ROOT).as_posix())
    return True


def generate(*, check: bool) -> list[str]:
    schema = _load_schema()
    rendered = (
        (PYTHON_PATH, _render_python(schema)),
        (TYPESCRIPT_PATH, _render_typescript(schema)),
    )
    return [
        path.relative_to(ROOT).as_posix()
        for path, expected in rendered
        if not _write_or_check(path, expected, check=check)
    ]


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    return 0 if not generate(check=args.check) else 1


if __name__ == "__main__":
    raise SystemExit(main())
